###Environment Setup

In [ ]:
!pip install -U umap-learn matplotlib scikit-learn

Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.9.post2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Collecting matplotlib
  Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (2.0.2)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.5.13)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from umap-learn) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.2->umap-learn) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 26.4 MB/s eta 0:00:00
Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 29.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn, matplotlib
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.0
    Uninstalling matplotlib-3.10.0:
      Successfully uninstalled matplotlib-3.10.0
Successfully installed matplotlib-3.10.7 scikit-learn-1.7.2

In [ ]:
!pip install -U spacy scispacy medspacy negspacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Collecting scispacy
  Downloading scispacy-0.6.2-py3-none-any.whl.metadata (20 kB)
Collecting medspacy
  Downloading medspacy-1.3.1.tar.gz (244 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.6/244.6 kB 8.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting negspacy
  Downloading negspacy-1.0.4.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.16.3)
Collecting conllu (from scispacy)
  Downloading conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy>=1.19.0 (from spacy)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.5.3)
Collecting nmslib-metabrainz==2.1.3 (from scispacy)
  Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (956 bytes)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.6.1)
Collecting pysbd (from scispacy)
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting pybind11>=2.2.3 (from nmslib-metabrainz==2.1.3->scispacy)
  Downloading pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from nmslib-metabrainz==2.1.3->scispacy) (5.9.5)
Collecting PyRuSH>=1.0.8 (from medspacy)
  Downloading pyrush-1.0.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from medspacy) (4.26.0)
Collecting medspacy_quickumls==3.2 (from medspacy)
  Downloading medspacy_quickumls-3.2.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.9/69.9 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting unidecode>=0.4.19 (from medspacy_quickumls==3.2->medspacy)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: nltk>=3.3 in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (3.9.1)
Collecting pysimstring (from medspacy_quickumls==3.2->medspacy)
  Downloading pysimstring-1.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (931 bytes)
Collecting medspacy_unqlite>=0.8.1 (from medspacy_quickumls==3.2->medspacy)
  Downloading medspacy_unqlite-0.9.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: pytest>=6 in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (8.4.2)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: Cython in /usr/local/lib/python3.12/dist-packages (from PyRuSH>=1.0.8->medspacy) (3.0.12)
Collecting PyFastNER>=1.0.8 (from PyRuSH>=1.0.8->medspacy)
  Downloading PyFastNER-1.0.10-py3-none-any.whl.metadata (15 kB)
Collecting quicksectx>=0.3.5 (from PyRuSH>=1.0.8->medspacy)
  Downloading quicksectx-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
Collecting loguru (from PyRuSH>=1.0.8->medspacy)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.3->scispacy) (3.6.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (0.30.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.3->medspacy_quickumls==3.2->medspacy) (2025.11.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Downloading scispacy-0.6.2-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.1 MB/s eta 0:00:00
Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 60.8 MB/s eta 0:00:00
Downloading pysbd-0.3.4-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 6.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 80.5 MB/s eta 0:00:00
Downloading pyrush-1.0.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (547 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.9/547.9 kB 40.1 MB/s eta 0:00:00
Downloading conllu-6.0.0-py3-none-any.whl (16 kB)
Downloading medspacy_unqlite-0.9.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (408 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 408.5/408.5 kB 33.4 MB/s eta 0:00:00
Downloading pybind11-3.0.1-py3-none-any.whl (293 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.6/293.6 kB 24.1 MB/s eta 0:00:00
Downloading PyFastNER-1.0.10-py3-none-any.whl (22 kB)
Downloading quicksectx-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.6 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 7.5 MB/s eta 0:00:00
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 2.2 MB/s eta 0:00:00
Downloading pysimstring-1.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 21.6 MB/s eta 0:00:00
Building wheels for collected packages: medspacy, medspacy_quickumls, negspacy
  Building wheel for medspacy (pyproject.toml) ... done
  Created wheel for medspacy: filename=medspacy-1.3.1-py3-none-any.whl size=313705 sha256=4ea69722098ee41b8a36a83e656a94cda0abe6e14eed7a2cad3281df6bb1be6e
  Stored in directory: /root/.cache/pip/wheels/54/ad/fd/49994aa138989a814164fed5afc6d8c7c3f1329d0aa0f327da
  Building wheel for medspacy_quickumls (setup.py) ... done
  Created wheel for medspacy_quickumls: filename=medspacy_quickumls-3.2-py3-none-any.whl size=98385 sha256=f267a2f40b26ff3bc0eaf558122bd3d5fdc04393d926be01926ed1b65025b7ba
  Stored in directory: /root/.cache/pip/wheels/5b/b8/96/ba72adae50099aa20ee8b11952fff415c8b82d86ca44528c92
  Building wheel for negspacy (pyproject.toml) ... done
  Created wheel for negspacy: filename=negspacy-1.0.4-py3-none-any.whl size=12631 sha256=732bc433cbb075160e6559047614a0fecbe17328f57d045e9228de4155ad0479
  Stored in directory: /root/.cache/pip/wheels/ca/89/69/61a6a722e19bb58f0ccdb62d879ec1dc4513310059d1fc0d1a
Successfully built medspacy medspacy_quickumls negspacy
Installing collected packages: pysimstring, medspacy_unqlite, unidecode, quicksectx, pysbd, pybind11, numpy, loguru, conllu, PyFastNER, nmslib-metabrainz, scispacy, PyRuSH, negspacy, medspacy_quickumls, medspacy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytensor 2.36.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed PyFastNER-1.0.10 PyRuSH-1.0.12 conllu-6.0.0 loguru-0.7.3 medspacy-1.3.1 medspacy_quickumls-3.2 medspacy_unqlite-0.9.8 negspacy-1.0.4 nmslib-metabrainz-2.1.3 numpy-1.26.4 pybind11-3.0.1 pysbd-0.3.4 pysimstring-1.3.0 quicksectx-0.4.1 scispacy-0.6.2 unidecode-1.4.0

In [ ]:
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz (119.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 MB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.8.0,>=3.7.4 (from en_core_sci_md==0.5.4)
  Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.12)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.4.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (25.0)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading langcodes-3.5.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2025.11.12)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (13.9.4)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.20.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.0.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.1.2)
Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 39.7 MB/s eta 0:00:00
Downloading langcodes-3.5.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 11.6 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (865 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.0/865.0 kB 45.0 MB/s eta 0:00:00
Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 80.0 MB/s eta 0:00:00
Building wheels for collected packages: en_core_sci_md
  Building wheel for en_core_sci_md (setup.py) ... done
  Created wheel for en_core_sci_md: filename=en_core_sci_md-0.5.4-py3-none-any.whl size=119157918 sha256=05086ccc1d527cd092b2526bce733abdc1ec0892d9840ea715c7841a0a38ab8d
  Stored in directory: /root/.cache/pip/wheels/1a/02/d9/4d4bda80f6b73c02ed057d4b3b99abaff286924a80b53c9d68
Successfully built en_core_sci_md
Installing collected packages: langcodes, blis, thinc, spacy, en_core_sci_md
  Attempting uninstall: blis
    Found existing installation: blis 1.3.3
    Uninstalling blis-1.3.3:
      Successfully uninstalled blis-1.3.3
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.10
    Uninstalling thinc-8.3.10:
      Successfully uninstalled thinc-8.3.10
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.11
    Uninstalling spacy-3.8.11:
      Successfully uninstalled spacy-3.8.11
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
medspacy 1.3.1 requires spacy<4.0,>=3.8; python_version >= "3.12", but you have spacy 3.7.5 which is incompatible.
pyrush 1.0.12 requires spacy>=3.8; python_version >= "3.12", but you have spacy 3.7.5 which is incompatible.
Successfully installed blis-0.7.11 en_core_sci_md-0.5.4 langcodes-3.5.1 spacy-3.7.5 thinc-8.2.5

In [ ]:
!pip install -U pip setuptools wheel

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (75.2.0)
Collecting setuptools
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.45.1)
Downloading pip-25.3-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.1 MB/s eta 0:00:00
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
pyrush 1.0.12 requires spacy>=3.8; python_version >= "3.12", but you have spacy 3.7.5 which is incompatible.
pytensor 2.35.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed pip-25.3 setuptools-80.9.0

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 36.0 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [ ]:
# Clip Style Text Embedder Setup
!pip install -U transformers torch sentencepiece tqdm

Collecting transformers
  Using cached transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cu126)
Collecting torch
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch) (3.3.20)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch)
  Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Using cached transformers-4.57.3-py3-none-any.whl (12.0 MB)
Using cached tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl (899.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 14.3 MB/s  0:01:20
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 16.2 MB/s  0:00:29
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 19.5 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 16.1 MB/s  0:00:05
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 29.4 MB/s  0:00:00
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 20.6 MB/s  0:00:09
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 11.6 MB/s  0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.8 MB/s  0:00:04
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 13.2 MB/s  0:00:20
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 17.3 MB/s  0:00:16
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 20.0 MB/s  0:00:01
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 12.3 MB/s  0:00:13
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, tokenizers, nvidia-cusolver-cu12, transformers, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.5.0
    Uninstalling triton-3.5.0:
      Successfully uninstalled triton-3.5.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.6.77
    Uninstalling nvidia-nvtx-cu12-12.6.77:
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.6.85
    Uninstalling nvidia-nvjitlink-cu12-12.6.85:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.6.85
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufile-cu12
    Found existing installation: nvidia-cufile-cu12 1.11.1.6
    Uninstalling nvidia-cufile-cu12-1.11.1.6:
      Successfully uninstalled nvidia-cufile-cu12-1.11.1.6
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.77
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.4.1
    Uninstalling nvidia-cublas-cu12-12.6.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4
    Uninstalling nvidia-cufft-cu12-11.3.0.4:
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2
  Attempting uninstall: torch
    Found existing installation: torch 2.9.0+cu126
    Uninstalling torch-2.9.0+cu126:
      Successfully uninstalled torch-2.9.0+cu126
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [torch]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.9.0+cu126 requires torch==2.9.0, but you have torch 2.9.1 which is incompatible.
torchvision 0.24.0+cu126 requires torch==2.9.0, but you have torch 2.9.1 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvtx-cu12-12.8.90 tokenizers-0.22.1 torch-2.9.1 transformers-4.57.3 triton-3.5.1

In [ ]:
!pip install -U open_clip_torch timm

Collecting open_clip_torch
  Downloading open_clip_torch-3.2.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (1.0.22)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (0.24.0+cu126)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (2025.11.3)
Collecting ftfy (from open_clip_torch)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (4.67.1)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (0.36.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from open_clip_torch) (0.7.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from timm) (6.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->open_clip_torch) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0->open_clip_torch) (1.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy->open_clip_torch) (0.2.14)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->open_clip_torch) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->open_clip_torch) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->open_clip_torch) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0->open_clip_torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->open_clip_torch) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->open_clip_torch) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->open_clip_torch) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub->open_clip_torch) (2025.11.12)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision->open_clip_torch) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision->open_clip_torch) (11.3.0)
Downloading open_clip_torch-3.2.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 8.0 MB/s  0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Installing collected packages: ftfy, open_clip_torch
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [open_clip_torch]
Successfully installed ftfy-6.3.1 open_clip_torch-3.2.0

In [ ]:
# BioClinical BERT Setup
!pip install -U transformers sentence-transformers torch tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Collecting transformers
  Downloading transformers-4.57.5-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cu126)
Collecting torch
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch) (3.3.20)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch)
  Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2026.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Downloading transformers-4.57.5-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 88.1 MB/s eta 0:00:00
Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl (899.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.1 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 1.1 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 29.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.2 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 35.5 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 25.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 10.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 14.0 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 3.7 MB/s eta 0:00:00
Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 7.6 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cusolver-cu12, transformers, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.5.0
    Uninstalling triton-3.5.0:
      Successfully uninstalled triton-3.5.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.6.77
    Uninstalling nvidia-nvtx-cu12-12.6.77:
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.6.85
    Uninstalling nvidia-nvjitlink-cu12-12.6.85:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.6.85
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufile-cu12
    Found existing installation: nvidia-cufile-cu12 1.11.1.6
    Uninstalling nvidia-cufile-cu12-1.11.1.6:
      Successfully uninstalled nvidia-cufile-cu12-1.11.1.6
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.77
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.4.1
    Uninstalling nvidia-cublas-cu12-12.6.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4
    Uninstalling nvidia-cufft-cu12-11.3.0.4:
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.3
    Uninstalling transformers-4.57.3:
      Successfully uninstalled transformers-4.57.3
  Attempting uninstall: torch
    Found existing installation: torch 2.9.0+cu126
    Uninstalling torch-2.9.0+cu126:
      Successfully uninstalled torch-2.9.0+cu126
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.9.0+cu126 requires torch==2.9.0, but you have torch 2.9.1 which is incompatible.
torchvision 0.24.0+cu126 requires torch==2.9.0, but you have torch 2.9.1 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvtx-cu12-12.8.90 torch-2.9.1 transformers-4.57.5 triton-3.5.1

In [ ]:
import numpy as np
import pandas as pd
import re
import spacy
import scispacy
from negspacy.negation import Negex
from tqdm import tqdm
from PIL import Image

import torch
import torch.nn.functional as F

from transformers import CLIPModel, CLIPProcessor
from sentence_transformers import SentenceTransformer
import torchvision.transforms as T
from transformers import AutoModel

import matplotlib.pyplot as plt
from umap import UMAP

### Dataset Analysis and Processing

In [ ]:
reports = pd.read_csv('/content/drive/MyDrive/comp-final-project/indiana_reports.csv')

In [ ]:
reports.head()

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

In [ ]:
features = reports[['uid','findings','impression']]
features.head(10)

,uid,findings,impression
0,1,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.
5,6,Heart size and mediastinal contour are within ...,No acute cardiopulmonary findings.
6,7,The cardiac contours are normal. XXXX basilar ...,Basilar atelectasis. No confluent lobar consol...
7,8,"The heart, pulmonary XXXX and mediastinum are ...",No acute cardiopulmonary disease.
8,9,The XXXX examination consists of frontal and l...,Increased size of density in the left cardioph...
9,10,The cardiomediastinal silhouette is within nor...,No acute cardiopulmonary process.

In [ ]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3851 entries, 0 to 3850
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         3851 non-null   int64
 1   findings    3337 non-null   object
 2   impression  3820 non-null   object
dtypes: int64(1), object(2)
memory usage: 90.4+ KB

In [ ]:
features.dropna(subset=['findings','impression'],inplace=True)
features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3331 entries, 0 to 3848
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         3331 non-null   int64
 1   findings    3331 non-null   object
 2   impression  3331 non-null   object
dtypes: int64(1), object(2)
memory usage: 104.1+ KB

/tmp/ipython-input-1006705488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features.dropna(subset=['findings','impression'],inplace=True)

In [ ]:
features.head()

,uid,findings,impression
0,1,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
3,4,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.
5,6,Heart size and mediastinal contour are within ...,No acute cardiopulmonary findings.

In [ ]:
def process_report(text):

  # regex masks
  x_mask_pattern = re.compile(r"X{2,}")
  punct_pattern =  re.compile(r"[^a-zA-Z0-9,\s\.]")
  num_bullets_pattern = re.compile(r"^\s*\d+\s*[\.\)]\s*",re.MULTILINE)
  tab_spacing_pattern = re.compile(r"\s+")


  # split the text into sentences
  sentences = re.split(r'(?<=[\.\?!])\s+', text)

  processed_sents = []

  for sent in sentences:
    # regex cleanup
    sent = x_mask_pattern.sub("",sent)
    sent = punct_pattern.sub(" ",sent)
    sent = num_bullets_pattern.sub("",sent)
    sent = tab_spacing_pattern.sub(" ",sent)

    if len(sent) > 2:
      processed_sents.append(sent)


  processed_text = " ".join(processed_sents).lower().strip()



  return processed_text

In [ ]:
cleaned_findings = features['findings'].apply(process_report)
cleaned_findings

0       the cardiac silhouette and mediastinum size ar...
1       borderline cardiomegaly. midline sternotomy . ...
3       there are diffuse bilateral interstitial and a...
4       the cardiomediastinal silhouette and pulmonary...
5       heart size and mediastinal contour are within ...
                              ...
3844    the heart is mildly enlarged. left hemidiaphra...
3845    similar mild cardiomegaly. of the pulmonary va...
3846    the cardiomediastinal silhouette and pulmonary...
3847    the lungs are clear. heart size is normal. no ...
3848    heart size within normal limits. small, nodula...
Name: findings, Length: 3331, dtype: object

In [ ]:
cleaned_impressions = features['impression'].apply(process_report)
cleaned_impressions

0                                        normal chest x .
1                            no acute pulmonary findings.
3       bullous emphysema and interstitial fibrosis. p...
4                   no acute cardiopulmonary abnormality.
5                      no acute cardiopulmonary findings.
                              ...
3844       borderline cardiomegaly without acute disease.
3845             mild cardiomegaly with of early failure.
3846    interval resolution of bibasilar airspace dise...
3847    clear lungs. no acute cardiopulmonary abnormal...
3848        no acute findings, no evidence for active tb.
Name: impression, Length: 3331, dtype: object

In [ ]:
cleaned_text = pd.DataFrame(
    {
        'uid': features['uid'],
        'findings' : cleaned_findings,
        'impression' : cleaned_impressions
    }
)
cleaned_text

,uid,findings,impression
0,1,the cardiac silhouette and mediastinum size ar...,normal chest x .
1,2,borderline cardiomegaly. midline sternotomy . ...,no acute pulmonary findings.
3,4,there are diffuse bilateral interstitial and a...,bullous emphysema and interstitial fibrosis. p...
4,5,the cardiomediastinal silhouette and pulmonary...,no acute cardiopulmonary abnormality.
5,6,heart size and mediastinal contour are within ...,no acute cardiopulmonary findings.
...,...,...,...
3844,3993,the heart is mildly enlarged. left hemidiaphra...,borderline cardiomegaly without acute disease.
3845,3994,similar mild cardiomegaly. of the pulmonary va...,mild cardiomegaly with of early failure.
3846,3995,the cardiomediastinal silhouette and pulmonary...,interval resolution of bibasilar airspace dise...
3847,3996,the lungs are clear. heart size is normal. no ...,clear lungs. no acute cardiopulmonary abnormal...
3848,3997,"heart size within normal limits. small, nodula...","no acute findings, no evidence for active tb."

###Text Embedding Analysis

1. Reports

In [ ]:
raw_report = pd.DataFrame(
    {
        'uid' : features['uid'],
        'diagnosis' : features['findings'] + " " + features['impression'],
    }
)

In [ ]:
raw_report['diagnosis'] = raw_report['diagnosis'].str.lower()
print(raw_report.iloc[2]['diagnosis'])

there are diffuse bilateral interstitial and alveolar opacities consistent with chronic obstructive lung disease and bullous emphysema. there are irregular opacities in the left lung apex, that could represent a cavitary lesion in the left lung apex.there are streaky opacities in the right upper lobe, xxxx scarring. the cardiomediastinal silhouette is normal in size and contour. there is no pneumothorax or large pleural effusion. 1. bullous emphysema and interstitial fibrosis. 2. probably scarring in the left apex, although difficult to exclude a cavitary lesion. 3. opacities in the bilateral upper lobes could represent scarring, however the absence of comparison exam, recommend short interval followup radiograph or ct thorax to document resolution.

In [ ]:
clean_report = pd.DataFrame(
    {
        'uid' : features['uid'],
        'diagnosis' : cleaned_text['findings'] + " " + cleaned_text['impression'],
    }
)

In [ ]:
clean_report['diagnosis'] = clean_report['diagnosis'].str.lower()
print(clean_report.iloc[2]['diagnosis'])

there are diffuse bilateral interstitial and alveolar opacities consistent with chronic obstructive lung disease and bullous emphysema. there are irregular opacities in the left lung apex, that could represent a cavitary lesion in the left lung apex.there are streaky opacities in the right upper lobe, scarring. the cardiomediastinal silhouette is normal in size and contour. there is no pneumothorax or large pleural effusion. bullous emphysema and interstitial fibrosis. probably scarring in the left apex, although difficult to exclude a cavitary lesion. opacities in the bilateral upper lobes could represent scarring, however the absence of comparison exam, recommend short interval followup radiograph or ct thorax to document resolution.

In [ ]:
clean_report.head()

   uid                                          diagnosis
0    1  the cardiac silhouette and mediastinum size ar...
1    2  borderline cardiomegaly. midline sternotomy . ...
3    4  there are diffuse bilateral interstitial and a...
4    5  the cardiomediastinal silhouette and pulmonary...
5    6  heart size and mediastinal contour are within ...

### MedClip Text Embedder vs BioClinicalBERT Text Embedder on RAW Reports

In [ ]:
# minimal cleaning
def minimal_clean_for_embed(text):
  text = text.lower()
  text = re.sub(r"\s+", " ", text)  # remove multiple spaces
  text = re.sub(r"x{2,}", "", text) # remove PHI Masking
  text = text.strip()

  return text

In [ ]:
raw_report['min_clean_diagnosis'] = raw_report['diagnosis'].apply(minimal_clean_for_embed)
raw_report.head()

,uid,diagnosis,min_clean_diagnosis
0,1,the cardiac silhouette and mediastinum size ar...,the cardiac silhouette and mediastinum size ar...
1,2,borderline cardiomegaly. midline sternotomy xx...,borderline cardiomegaly. midline sternotomy . ...
3,4,there are diffuse bilateral interstitial and a...,there are diffuse bilateral interstitial and a...
4,5,the cardiomediastinal silhouette and pulmonary...,the cardiomediastinal silhouette and pulmonary...
5,6,heart size and mediastinal contour are within ...,heart size and mediastinal contour are within ...

In [ ]:
raw_report['min_clean_diagnosis'].values[0]

'the cardiac silhouette and mediastinum size are within normal limits. there is no pulmonary edema. there is no focal consolidation. there are no  of a pleural effusion. there is no evidence of pneumothorax. normal chest x-.'

In [ ]:
sample_reports = raw_report.sample(n=1000, random_state=99).reset_index(drop=True)
sample_reports.head()

,uid,diagnosis,min_clean_diagnosis
0,437,there are postoperative changes of sternotomy....,there are postoperative changes of sternotomy....
1,1330,heart size and cardiomediastinal silhouette ar...,heart size and cardiomediastinal silhouette ar...
2,1932,heart size and mediastinal contour are normal....,heart size and mediastinal contour are normal....
3,260,lungs are clear bilaterally. cardiac and media...,lungs are clear bilaterally. cardiac and media...
4,1643,3 images. heart size and pulmonary vascular en...,3 images. heart size and pulmonary vascular en...

1. CLIP Style Text Encoder

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

CLIP_NAME = "openai/clip-vit-base-patch16"

clip_model = CLIPModel.from_pretrained(CLIP_NAME).to(device)
clip_processor = CLIPProcessor.from_pretrained(CLIP_NAME)

clip_model.eval()

print("CLIP model loaded successfully")

Using device: cpu
CLIP model loaded successfully

In [ ]:
def encode_clip_text(texts, model, processor, device, batch_size=16):
    all_embeddings = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts[i:i+batch_size]

        inputs = processor(
            text=batch,
            padding=True,
            truncation=True,
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            text_features = model.get_text_features(**inputs)
            text_features = F.normalize(text_features, p=2, dim=1)

        all_embeddings.append(text_features.cpu().numpy())

    return np.vstack(all_embeddings)

In [ ]:
clip_embedd_text = sample_reports["min_clean_diagnosis"].tolist()

In [ ]:
clip_embeds = encode_clip_text(
    clip_embedd_text,
    clip_model,
    clip_processor,
    device=device,
    batch_size=16
)

print(clip_embeds.shape)

100%|██████████| 63/63 [02:07<00:00,  2.02s/it]

(1000, 512)

In [ ]:
sample_reports["emb_clip"] = list(clip_embeds)
sample_reports.head()

,uid,diagnosis,min_clean_diagnosis,emb_clip
0,437,there are postoperative changes of sternotomy....,there are postoperative changes of sternotomy....,"[0.03631397, 0.036697753, -0.029660735, -0.006..."
1,1330,heart size and cardiomediastinal silhouette ar...,heart size and cardiomediastinal silhouette ar...,"[0.0025161859, 0.06836397, -0.0067069093, -0.0..."
2,1932,heart size and mediastinal contour are normal....,heart size and mediastinal contour are normal....,"[0.001245784, 0.079612345, -0.019224249, -0.01..."
3,260,lungs are clear bilaterally. cardiac and media...,lungs are clear bilaterally. cardiac and media...,"[0.0024294932, 0.029523471, -0.037089556, 0.00..."
4,1643,3 images. heart size and pulmonary vascular en...,3 images. heart size and pulmonary vascular en...,"[-0.0025480986, 0.06958377, -0.02554206, -0.01..."

2. BioCLinical BERT Text Embedder

In [ ]:
bioclin_model = SentenceTransformer("emilyalsentzer/Bio_ClinicalBERT")
bioclin_model.get_sentence_embedding_dimension()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name emilyalsentzer/Bio_ClinicalBERT. Creating a new one with mean pooling.

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/436M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

768

In [ ]:
txt_for_embedding = clean_report['diagnosis'].astype(str).tolist()
len(txt_for_embedding)

3331

In [ ]:
from sentence_transformers.util import normalize_embeddings
bc_bert_embeds = bioclin_model.encode(
    txt_for_embedding,
    batch_size = 16,
    show_progress_bar = True,
    normalize_embeddings = True
)

Batches:   0%|          | 0/209 [00:00<?, ?it/s]

In [ ]:
clean_report['diagnosis_embeds'] = list(bc_bert_embeds)

In [ ]:
clean_report.head()

,uid,diagnosis,diagnosis_embeds
0,1,the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,2,borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,4,there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
4,5,the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
5,6,heart size and mediastinal contour are within ...,"[0.011237842, -0.02500179, 0.011986025, 0.0276..."

In [ ]:
text_embeddings = clean_report
text_embeddings.head()

,uid,diagnosis,diagnosis_embeds
0,1,the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,2,borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,4,there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
4,5,the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
5,6,heart size and mediastinal contour are within ...,"[0.011237842, -0.02500179, 0.011986025, 0.0276..."

In [ ]:
out_path = "/content/drive/MyDrive/comp-final-project/report_text_embeddings_with_text.pkl"

text_embeddings.to_pickle(out_path)

print(f'Text embeddings saved to : {out_path}')

Text embeddings saved to : /content/drive/MyDrive/comp-final-project/report_text_embeddings_with_text.pkl

### MedSpacy Entity Extraction Setup

In [ ]:
# configuring NLP pipeline
cxray_nlp = spacy.load("en_core_sci_md")
print(cxray_nlp.pipe_names)
cxray_nlp.add_pipe(
    "negex",
    config={
        "ent_types": ["ENTITY"]
    },
    last=True
)

/usr/local/lib/python3.12/dist-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

['tok2vec', 'tagger', 'attribute_ruler', 'lemmatizer', 'parser', 'ner']

In [ ]:
doc = cxray_nlp("No evidence of pneumonia or pleural effusion.")

for ent in doc.ents:
    print(ent.text, ent.label_, ent._.negex)

No evidence ENTITY False
pneumonia ENTITY True
pleural effusion ENTITY True

In [ ]:
# minimal cleaning that is required for NER
def minimal_clean(text):

  text = re.sub(r"\s+", " ", text)  # remove multiple spaces
  text = re.sub(r"X{2,}", "", text) # remove PHI Masking
  text = text.lower()
  text = text.strip()

  return text

In [ ]:
# Normalizing Labels generated through Spacy

def normalize_entity(text):
  ''' Need to normalize returned entity text to
  make it consistent for use as a label '''

  text = text.lower()
  text = text.strip()

  text = re.sub(r"[^a-z0-9\s\-]", "", text)  # keep only letters, digits, hyphen, space
  text = re.sub(r"\s+", "_", text)  # replace space with underscore

  return text

In [ ]:
# Extract Weak Supervision Labels through sciSpacy
# Disease whitelist Ontology-guided weak supervision

'''
Conceptual Working
normalize_entity() → “pneumonia” and “Pneumonia.” → pneumonia

ent._.negex → True = absent, False = present
'''
CXR_DISEASE_VOCAB = {
    "pneumonia", "pneumothorax", "pleural_effusion", "atelectasis",
    "cardiomegaly", "edema", "emphysema", "fibrosis", "consolidation",
    "opacity", "nodule", "mass", "infiltrate", "effusion",
    "airspace_disease", "interstitial_disease", "injury"
}

def extract_labels(text, nlp):

  clean_text = minimal_clean(text)

  doc = nlp(clean_text) # extract affirmation/negation for suspected condition

  affirmed_conditions = set()
  negated_conditions = set()

  for entity in doc.ents:
    label = normalize_entity(entity.text)

    if label not in CXR_DISEASE_VOCAB:
      continue

    if len(label) < 4:
      continue

    if entity._.negex:
      negated_conditions.add(label)
    else:
      affirmed_conditions.add(label)

  return affirmed_conditions, negated_conditions

In [ ]:
# Apply function to Report

affirmed_condition = []
negated_condition = []

for text in raw_report['diagnosis']:
  affirmed, negated = extract_labels(text, cxray_nlp)
  affirmed_condition.append(affirmed)
  negated_condition.append(negated)

raw_report['affirmed_condtions'] = affirmed_condition
raw_report['negated_condition'] = negated_condition

raw_report.head()

,uid,diagnosis,affirmed_condtions,negated_condition
0,1,the cardiac silhouette and mediastinum size ar...,{},"{mediastinum_size, normal_limits, cardiac_silh..."
1,2,borderline cardiomegaly. midline sternotomy xx...,{},"{findings, lungs, midline_sternotomy_xxxx, bor..."
3,4,there are diffuse bilateral interstitial and a...,{},"{pneumothorax, left_lung, contour, upper_lobes..."
4,5,the cardiomediastinal silhouette and pulmonary...,{},"{biapical_pleural_thickening, normal_limits, p..."
5,6,heart size and mediastinal contour are within ...,{},"{pleural_effusion, normal_limits, pneumothorax..."

### Positive Case Testing Scenario

In [ ]:
pos_row = raw_report.loc[
    raw_report["diagnosis"].str.contains(
        "there is cardiomegaly|consistent with pneumonia|moderate .*effusion|edema is noted",
        case=False, na=False
    )
].head(1)

print(pos_row["diagnosis"].values[0])

The heart is within normal limits in size. Surgical suture material projects over the right lung apex. The lungs are hyperlucent and hyperinflated compatible with emphysema. There is left lower lobe airspace disease identified. There is moderate left pleural effusion and small right pleural effusion. No visualized pneumothorax. 1. Left lower lobe airspace disease and bilateral pleural effusions, left greater than right. This may be secondary to inhalational injury. Recommend followup to ensure complete resolution.

In [ ]:
doc = cxray_nlp(pos_row["diagnosis"].values[0])

print("---- ENTITIES ----")
for ent in doc.ents:
    print(ent.text, ent.label_)

---- ENTITIES ----
heart ENTITY
limits ENTITY
size ENTITY
Surgical suture material ENTITY
right lung apex ENTITY
lungs ENTITY
hyperlucent ENTITY
hyperinflated ENTITY
emphysema ENTITY
left lower lobe airspace disease ENTITY
identified ENTITY
moderate ENTITY
left pleural effusion ENTITY
small right pleural effusion ENTITY
No visualized ENTITY
pneumothorax ENTITY
Left lower lobe airspace disease ENTITY
bilateral ENTITY
pleural effusions ENTITY
right ENTITY
secondary ENTITY
inhalational injury ENTITY
followup ENTITY
complete ENTITY
resolution ENTITY

### Retrival through EMbeddings POC

In [ ]:
import faiss
import pandas as pd
import numpy as np
import ast

In [ ]:
sample_reports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uid                  1000 non-null   int64
 1   diagnosis            1000 non-null   object
 2   min_clean_diagnosis  1000 non-null   object
 3   emb_clip             1000 non-null   object
 4   bert_embeddings      1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [ ]:
# Building vector storage with FAISS

bert_embeds = np.vstack(sample_reports['bert_embeddings'].values).astype('float32')
clip_embeds = np.vstack(sample_reports['emb_clip'].values).astype('float32')

bert_idx = faiss.IndexFlatIP(bert_embeds.shape[1])
clip_idx = faiss.IndexFlatIP(clip_embeds.shape[1])

bert_idx.add(bert_embeds)
clip_idx.add(clip_embeds)

In [ ]:
query_pool = sample_reports[
    sample_reports["diagnosis"].str.contains(
        "pneumonia|effusion|cardiomegaly|atelectasis|edema|emphysema|consolidation",
        case=False, na=False
    )
]

In [ ]:
query_pool

,uid,diagnosis,min_clean_diagnosis,emb_clip,bert_embeddings
0,437,there are postoperative changes of sternotomy....,there are postoperative changes of sternotomy....,"[0.03631397, 0.036697753, -0.029660735, -0.006...","[0.009954476, -0.02781623, 0.009157939, 0.0169..."
1,1330,heart size and cardiomediastinal silhouette ar...,heart size and cardiomediastinal silhouette ar...,"[0.0025161859, 0.06836397, -0.0067069093, -0.0...","[0.010551789, -0.026771992, 0.014932178, 0.026..."
2,1932,heart size and mediastinal contour are normal....,heart size and mediastinal contour are normal....,"[0.001245784, 0.079612345, -0.019224249, -0.01...","[0.008806968, -0.013635329, 0.020984527, 0.025..."
3,260,lungs are clear bilaterally. cardiac and media...,lungs are clear bilaterally. cardiac and media...,"[0.0024294932, 0.029523471, -0.037089556, 0.00...","[0.017252807, -0.038597483, 0.014909176, 0.019..."
4,1643,3 images. heart size and pulmonary vascular en...,3 images. heart size and pulmonary vascular en...,"[-0.0025480986, 0.06958377, -0.02554206, -0.01...","[0.022123788, -0.028018666, 0.0043225614, 0.02..."
...,...,...,...,...,...
991,2545,the trachea is midline. the cardiomediastinal ...,the trachea is midline. the cardiomediastinal ...,"[0.0013365811, 0.07446153, -0.0067176996, -0.0...","[0.01469646, -0.008659491, 0.014139751, 0.0272..."
994,1901,the xxxx examination consists of frontal and l...,the examination consists of frontal and later...,"[0.017125532, 0.02910198, -0.015780134, 0.0174...","[0.01237323, -0.024415608, 0.004870905, 0.0227..."
995,1676,heart size and mediastinal contour within norm...,heart size and mediastinal contour within norm...,"[0.0043631974, 0.044129986, -0.04278083, 0.013...","[0.02260406, -0.013081468, 0.017426876, 0.0171..."
998,1048,"heart size, mediastinal contour, and pulmonary...","heart size, mediastinal contour, and pulmonary...","[0.03398223, 0.03847225, -0.043938905, 0.00701...","[0.015382047, -0.027581338, 0.017923804, 0.025..."
999,465,normal cardiomediastinal contours. right lower...,normal cardiomediastinal contours. right lower...,"[0.011625308, 0.06809479, -0.020022577, 0.0001...","[0.0141641265, -0.0061345417, -0.0034384506, 0..."

In [ ]:
# Preparing the query
query_record = query_pool.sample(1,random_state=33)
print(query_record[['uid','min_clean_diagnosis']])

q_idx = query_record.index[0]
q_uid = query_record['uid']
q_text = query_record['min_clean_diagnosis'].values[0]

      uid                                min_clean_diagnosis
236  2670  hyperexpanded lungs with flattened hemidiaphra...

In [ ]:
# Fetching query embeddings
q_bert = bert_embeds[q_idx].reshape(1,-1)
q_clip = clip_embeds[q_idx].reshape(1,-1)
print(q_bert.shape, q_clip.shape)

(1, 768) (1, 512)

In [ ]:
# FAISS Retrieval
D_bert, I_bert = bert_idx.search(q_bert, k=6)
D_clip, I_clip = clip_idx.search(q_clip, k=6)

In [ ]:
print("\n=========== BIOCLINICALBERT RETRIEVAL ===========\n")

for rank, idx in enumerate(I_bert[0][1:], 1):
    print(f"--- Rank {rank} | CosSim = {D_bert[0][rank]:.4f} ---")
    print(sample_reports.loc[idx, "min_clean_diagnosis"], "\n")

=========== BIOCLINICALBERT RETRIEVAL ===========

--- Rank 1 | CosSim = 0.9784 ---
the lungs remain hyperexpanded. there are persistent  bilateral lower lobe opacities,  subsegmental atelectasis and scarring. no  focal infiltrate is identified. there is no pleural effusion or pneumothorax. normal heart size. there are minimal degenerative changes of the spine. 1. no acute findings. 2. bibasilar subsegmental atelectasis or scarring. 3. emphysema.

--- Rank 2 | CosSim = 0.9774 ---
the heart is normal in size. the mediastinum is stable. rectal balloon is noted. lungs are mildly hypoinflated. there is again eventration of the hemidiaphragms/ bochdalek hernia, posteriorly as seen on the lateral projection. bilateral pleural thickening is noted. there are streaky opacities in the lung bases unchanged,  chronic atelectasis. mild bilateral streaky opacities,  atelectasis. no acute infiltrate.

--- Rank 3 | CosSim = 0.9768 ---
there are  opacities in the left lung,  subsegmental atelectasis.  opacities overlying the left lung base on the frontal   reflect epicardial fat  and overlying breast tissue. there is no focal airspace consolidation. no pleural effusion or pneumothorax. heart size is at the upper limits of normal. there are diffuse degenerative changes of the spine. no acute findings. left mid lung subsegmental atelectasis.

--- Rank 4 | CosSim = 0.9763 ---
there is hyperexpansion, hyperlucency of both lungs, as well as flattening of the diaphragm consistent with chronic emphysematous lung disease. no focal consolidation, pneumothorax, or large pleural effusion identified (blunting of costophrenic recesses bilaterally may represent small effusions or pleural thickening/scar. stable calcified mediastinal and hilar lymph  and a left basilar calcified granuloma. acute osseous abnormality. the mediastinal silhouette stable. changes of chronic emphysematous lung disease without acute cardiopulmonary abnormality identified.

--- Rank 5 | CosSim = 0.9763 ---
sequelae of old granulomatous disease. lungs are overall hyperexpanded with flattening of the diaphragms. no focal consolidation. prominent interstitial markings are again noted which are predominantly lower lobe and peripheral suggesting pulmonary fibrosis. this appearance is overall not significantly . no pleural effusions or pneumothoraces. heart and mediastinum are stable with atherosclerotic vascular disease. degenerative changes in the thoracic spine. 1. overall stable appearance of the chest suggesting pulmonary fibrosis.

In [ ]:
print("\n================ CLIP RETRIEVAL ================\n")

for rank, idx in enumerate(I_clip[0][1:], 1):
    print(f"--- Rank {rank} | CosSim = {D_clip[0][rank]:.4f} ---")
    print(sample_reports.loc[idx, "diagnosis"], "\n")

================ CLIP RETRIEVAL ================

--- Rank 1 | CosSim = 0.9229 ---
the lungs are hyperexpanded consistent with emphysema. the heart size and pulmonary vascularity appear within normal limits. no pneumothorax or pleural effusion is seen. patchy airspace disease is present in the right middle lobe. degenerative changes are present spine. 1. hyperexpanded lungs suggesting emphysema. 2. patchy right middle lobe airspace disease. may represent pneumonia. followup examination is suggested following treatment to confirm clearing of the opacities. a 4 to 6 xxxx post treatment interval film would be reasonable to allow clearing of inflammatory opacities.

--- Rank 2 | CosSim = 0.9149 ---
hyperexpansion of the lungs with hyperlucency and flattening of hemidiaphragms suggestive of chronic emphysematous lung disease. heart size within normal limits. bibasilar, right greater than left atelectasis/airspace disease noted. no pneumothorax or large pleural effusion. no acute bony abnormality. chronic emphysematous lung disease with mild bibasilar, right greater than left airspace disease/atelectasis.

--- Rank 3 | CosSim = 0.9022 ---
hyperinflated lungs with flattened diaphragm and increased retrosternal airspace. scattered chronic appearing irregular interstitial markings with no focal alveolar consolidation, no definite pleural effusion seen. no typical findings of pulmonary edema. hyperinflated lungs, air trapping versus inspiratory xxxx.

--- Rank 4 | CosSim = 0.9009 ---
lungs are hyperinflated with interstitial changes of severe emphysema. there is an ill-defined pleural parenchymal opacity in the left upper lobe. this may represent scarring but is incompletely evaluated on the outside study, without coronal and sagittal reformats. there is mild xxxx scarring and/or atelectasis in the lung bases. lungs otherwise grossly clear. there is no pneumothorax or pleural effusion. heart size is normal. there are mild degenerative endplate changes in the thoracic spine. there is generalized osteopenia. 1. severe emphysema. 2. irregular, pleural-parenchymal opacity in left upper lobe. this may irregular pleural-parenchymal scarring, however, recommend comparison with more remote outside imaging, if available to determine long-term stability. if none are available, recommend short-term xxxx in 3 to 4 months. evaluation of coronal and sagittal reformatted images from the outside study would also be helpful. these were not xxxx available at the outside institution. malignancy cannot be confidently excluded on the available images.

--- Rank 5 | CosSim = 0.9002 ---
the lungs appear hyperexpanded suggesting emphysema. the heart size and pulmonary vascularity appear within normal limits. the lungs are free of focal airspace disease. calcified granuloma is identified. no pneumothorax or pleural effusion is seen. 1. hyperexpanded lungs. the pattern suggests emphysema. 2. no evidence of acute disease.

# Image Encoder

In [ ]:
!pip install torchxrayvision torchvision pillow

Collecting torchxrayvision
  Downloading torchxrayvision-1.4.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.24.0+cu126)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: torch>=1 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (2.9.0+cu126)
Requirement already satisfied: scikit-image>=0.16 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (0.25.2)
Requirement already satisfied: tqdm>=4 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (4.67.1)
Requirement already satisfied: numpy>=1 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (2.0.2)
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (2.2.2)
Requirement already satisfied: requests>=1 in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (2.32.4)
Requirement already satisfied: imageio in /usr/local/lib/python3.12/dist-packages (from torchxrayvision) (2.37.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1->torchxrayvision) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->torchxrayvision) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->torchxrayvision) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1->torchxrayvision) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=1->torchxrayvision) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=1->torchxrayvision) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=1->torchxrayvision) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=1->torchxrayvision) (2026.1.4)
Requirement already satisfied: scipy>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.16->torchxrayvision) (1.16.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.16->torchxrayvision) (2025.12.20)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.16->torchxrayvision) (25.0)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.16->torchxrayvision) (0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1->torchxrayvision) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1->torchxrayvision) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1->torchxrayvision) (3.0.3)
Downloading torchxrayvision-1.4.0-py3-none-any.whl (29.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.0/29.0 MB 14.0 MB/s eta 0:00:00
Installing collected packages: torchxrayvision
Successfully installed torchxrayvision-1.4.0

In [ ]:
import torch
import torchxrayvision as xrv
from PIL import Image
import torchvision.transforms as T
import numpy as np
import pandas as pd

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

Using device: cuda

In [ ]:
# Image Encoder Model
image_encoder = xrv.models.DenseNet(weights="densenet121-res224-all")
image_encoder = image_encoder.to(device)

image_encoder.eval()

Downloading weights...
If this fails you can run `wget https://github.com/mlmed/torchxrayvision/releases/download/v1/nih-pc-chex-mimic_ch-google-openi-kaggle-densenet121-d121-tw-lr001-rot45-tr15-sc15-seed0-best.pt -O /root/.torchxrayvision/models_data/nih-pc-chex-mimic_ch-google-openi-kaggle-densenet121-d121-tw-lr001-rot45-tr15-sc15-seed0-best.pt`
[██████████████████████████████████████████████████]

XRV-DenseNet121-densenet121-res224-all

In [ ]:
# Image Pre - Processing
image_pre_process = T.Compose([
    T.Resize((224,224)),
    T.ToTensor()
]
)

In [ ]:
# Image Loader
IMAGE_PATH = '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/1000_IM-0003-1001.dcm.png'

image = Image.open(IMAGE_PATH).convert('L')
image_tnsr = image_pre_process(image).unsqueeze(0).to(device)

image_tnsr.shape

torch.Size([1, 1, 224, 224])

In [ ]:
# Image Embedding
with torch.no_grad():
    image_embedding = image_encoder.features(image_tnsr)


image_embedding.shape

torch.Size([1, 1024, 7, 7])

In [ ]:
pooled_embedding = torch.nn.functional.adaptive_avg_pool2d(
    image_embedding, output_size=(1, 1)
)
pooled_embedding.shape

torch.Size([1, 1024, 1, 1])

In [ ]:
flattened_embedding = pooled_embedding.view(pooled_embedding.size(0), -1)
flattened_embedding.shape

torch.Size([1, 1024])

In [ ]:
normalized_embedding = torch.nn.functional.normalize(
    flattened_embedding, dim=1
)
normalized_embedding.shape

torch.Size([1, 1024])

In [ ]:
image_embedding = normalized_embedding.cpu().numpy().astype('float32')
image_embedding.shape

(1, 1024)

### Dataset And Data Loader for Images

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

# !unzip /content/drive/MyDrive/comp-final-project/images.zip -d /content/drive/MyDrive/comp-final-project/chest-xrays/

Streaming output truncated to the last 5000 lines.
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2198_IM-0808-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2199_IM-0809-0001-0002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/219_IM-0799-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/219_IM-0799-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/21_IM-0729-1001-0001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/21_IM-0729-1001-0002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2200_IM-0811-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2200_IM-0811-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2201_IM-0811-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2202_IM-0811-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2202_IM-0811-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2203_IM-0812-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2203_IM-0812-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2204_IM-0813-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2204_IM-0813-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2205_IM-0814-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2206_IM-0815-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2206_IM-0815-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2207_IM-0815-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2207_IM-0815-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2208_IM-0815-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2208_IM-0815-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2209_IM-0816-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2209_IM-0816-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/220_IM-0811-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/220_IM-0811-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/220_IM-0811-1003.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2210_IM-0817-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2210_IM-0817-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2211_IM-0818-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2211_IM-0818-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2212_IM-0819-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2212_IM-0819-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2213_IM-0819-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2213_IM-0819-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2214_IM-0819-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2215_IM-0820-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2215_IM-0820-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2216_IM-0821-85075001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2216_IM-0821-85075002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2217_IM-0822-0001-0001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2217_IM-0822-0001-0002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2218_IM-0823-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2218_IM-0823-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2218_IM-0823-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2219_IM-0823-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2219_IM-0823-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/221_IM-0817-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/221_IM-0817-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2220_IM-0824-4004.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2221_IM-0825-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2221_IM-0825-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2222_IM-0826-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2222_IM-0826-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2223_IM-0827-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2223_IM-0827-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2224_IM-0828-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2224_IM-0828-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2225_IM-0829-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2225_IM-0829-4001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2226_IM-0830-12001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2226_IM-0830-13001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2227_IM-0831-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2228_IM-0831-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2228_IM-0831-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2229_IM-0831-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2229_IM-0831-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/222_IM-0823-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/222_IM-0823-3003.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2230_IM-0831-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2230_IM-0831-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2231_IM-0831-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2231_IM-0831-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2231_IM-0831-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2232_IM-0832-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2232_IM-0832-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2233_IM-0832-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2233_IM-0832-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2234_IM-0833-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2234_IM-0833-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2235_IM-0833-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2235_IM-0833-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2236_IM-0833-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2236_IM-0833-2002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2237_IM-0834-2002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2237_IM-0834-3003.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2238_IM-0835-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2238_IM-0835-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2239_IM-0836-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2239_IM-0836-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/223_IM-0831-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/223_IM-0831-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2240_IM-0838-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2240_IM-0838-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2241_IM-0839-28001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2242_IM-0840-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2242_IM-0840-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2243_IM-0840-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2243_IM-0840-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2243_IM-0840-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2243_IM-0840-4001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2244_IM-0841-2002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2244_IM-0841-3003.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2245_IM-0842-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2245_IM-0842-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2246_IM-0843-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2246_IM-0843-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2247_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2247_IM-0844-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2248_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2248_IM-0844-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2249_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2249_IM-0844-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/224_IM-0837-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/224_IM-0837-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2250_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2251_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2252_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2252_IM-0844-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2253_IM-0845-1002001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2253_IM-0845-1003002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2254_IM-0846-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2255_IM-0847-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2255_IM-0847-4001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2256_IM-0848-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2256_IM-0848-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2256_IM-0848-4001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2257_IM-0849-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2257_IM-0849-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2258_IM-0849-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2258_IM-0849-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2259_IM-0850-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2259_IM-0850-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/225_IM-0844-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/225_IM-0844-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2260_IM-0852-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2260_IM-0852-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2261_IM-0852-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2261_IM-0852-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2262_IM-0852-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2262_IM-0852-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2263_IM-0853-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2263_IM-0853-4001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2264_IM-0854-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2264_IM-0854-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2265_IM-0855-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2265_IM-0855-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2266_IM-0855-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2266_IM-0855-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2266_IM-0855-3001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2267_IM-0856-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2267_IM-0856-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2268_IM-0857-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2268_IM-0857-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2269_IM-0858-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2269_IM-0858-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/226_IM-0851-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/226_IM-0851-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2270_IM-0859-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2270_IM-0859-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2271_IM-0860-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2272_IM-0861-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2272_IM-0861-2001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2273_IM-0861-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2273_IM-0861-1002.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2274_IM-0861-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2275_IM-0862-1001.dcm.png
  inflating: /content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2275_IM-0862-2001.dcm.png

In [ ]:
import torch
import os, glob
from PIL import Image
import skimage.io
import torchvision.transforms as T
from torchvision.transforms import InterpolationMode
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [ ]:

class XrayDataset(Dataset):

  def __init__(self, ROOT_PATH):

    self.ROOT_PATH = ROOT_PATH
    self.image_paths = sorted(glob.glob(os.path.join(ROOT_PATH, '*.png')))

    self.pre_process = T.Compose([
    T.Resize((224,224), interpolation=InterpolationMode.BILINEAR),
    T.ToTensor(),
    T.Lambda(lambda x: x * 2.0 - 1.0),
    ]
    )

    self.center_crop = xrv.datasets.XRayCenterCrop()
    self.resizer = xrv.datasets.XRayResizer(224)

  def _extract_uid(self, path):
    img_name = path.split('/')[-1]
    uid = int(img_name.split('_')[0])
    return uid

  def __len__(self):
    return(len(self.image_paths))

  def __getitem__(self, index):

    img_path = self.image_paths[index]
    uid = self._extract_uid(img_path)

    image = Image.open(img_path).convert('L')
    image_tnsr = self.pre_process(image)

    return uid, img_path, image_tnsr

In [ ]:
ROOT_PATH = '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/'
xray_dataset = XrayDataset(ROOT_PATH)

In [ ]:
print(f'Images in Dataset: {len(xray_dataset)}')

Images in Dataset: 7470

In [ ]:
uid, path, tnsr = xray_dataset[0]

print(uid)
print(path)
print(tnsr.shape)

1000
/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/1000_IM-0003-1001.dcm.png
torch.Size([1, 224, 224])

### IMAGE EMBEDDER PIPELINE
### WITH DATA LOADER

In [ ]:
data_loader = DataLoader(
    xray_dataset,
    batch_size=16,
    num_workers = 2,
    shuffle=False
    )

In [ ]:
print(f'Batches in Data Loader: {len(data_loader)}')

Batches in Data Loader: 467

In [ ]:
# Sanity Checks
uids, paths, images = next(iter(data_loader))
print(images.min().item(), images.max().item(), images.mean().item(), images.std().item())

-1.0 1.0 0.21473173797130585 0.5564430356025696

In [ ]:
import torch.nn.functional as F
import pandas as pd

In [ ]:
def generate_image_embeds(image_encoder, batch_images):

  # Features
  features = image_encoder.features(batch_images)

  # Average Pooling to Remove Spatial Grid Info
  pooled_features = F.adaptive_avg_pool2d(features,(1,1) )

  # Flatten Pooled Feature
  flat_features = pooled_features.view(pooled_features.size(0), -1)

  # Normalization
  normalized_features = F.normalize(flat_features, dim=1)

  return normalized_features

In [ ]:
#sanity check for image encoder
image_encoder.eval()

print('--- Sanity Check for Encoder Completed ---')
rows = []
batch_count = 0
with torch.no_grad():

  for uids, paths, images in data_loader:
    batch_count += 1
    imgs = images.to(device, non_blocking=True)

    img_embeds = generate_image_embeds(image_encoder, imgs)
    img_embeds = img_embeds.cpu().numpy().astype('float32')

    for uid, path, embedding in zip(uids.tolist(), paths, img_embeds):
      rows.append(
          {
              'uid': uid,
              'image_path': path,
              'image_embedding': embedding
          }
      )
    print(f'Processing Batch id: {batch_count}')

--- Sanity Check for Encoder Completed ---
Processing Batch id: 1
Processing Batch id: 2
Processing Batch id: 3
Processing Batch id: 4
Processing Batch id: 5
Processing Batch id: 6
Processing Batch id: 7
Processing Batch id: 8
Processing Batch id: 9
Processing Batch id: 10
Processing Batch id: 11
Processing Batch id: 12
Processing Batch id: 13
Processing Batch id: 14
Processing Batch id: 15
Processing Batch id: 16
Processing Batch id: 17
Processing Batch id: 18
Processing Batch id: 19
Processing Batch id: 20
Processing Batch id: 21
Processing Batch id: 22
Processing Batch id: 23
Processing Batch id: 24
Processing Batch id: 25
Processing Batch id: 26
Processing Batch id: 27
Processing Batch id: 28
Processing Batch id: 29
Processing Batch id: 30
Processing Batch id: 31
Processing Batch id: 32
Processing Batch id: 33
Processing Batch id: 34
Processing Batch id: 35
Processing Batch id: 36
Processing Batch id: 37
Processing Batch id: 38
Processing Batch id: 39
Processing Batch id: 40
Processing Batch id: 41
Processing Batch id: 42
Processing Batch id: 43
Processing Batch id: 44
Processing Batch id: 45
Processing Batch id: 46
Processing Batch id: 47
Processing Batch id: 48
Processing Batch id: 49
Processing Batch id: 50
Processing Batch id: 51
Processing Batch id: 52
Processing Batch id: 53
Processing Batch id: 54
Processing Batch id: 55
Processing Batch id: 56
Processing Batch id: 57
Processing Batch id: 58
Processing Batch id: 59
Processing Batch id: 60
Processing Batch id: 61
Processing Batch id: 62
Processing Batch id: 63
Processing Batch id: 64
Processing Batch id: 65
Processing Batch id: 66
Processing Batch id: 67
Processing Batch id: 68
Processing Batch id: 69
Processing Batch id: 70
Processing Batch id: 71
Processing Batch id: 72
Processing Batch id: 73
Processing Batch id: 74
Processing Batch id: 75
Processing Batch id: 76
Processing Batch id: 77
Processing Batch id: 78
Processing Batch id: 79
Processing Batch id: 80
Processing Batch id: 81
Processing Batch id: 82
Processing Batch id: 83
Processing Batch id: 84
Processing Batch id: 85
Processing Batch id: 86
Processing Batch id: 87
Processing Batch id: 88
Processing Batch id: 89
Processing Batch id: 90
Processing Batch id: 91
Processing Batch id: 92
Processing Batch id: 93
Processing Batch id: 94
Processing Batch id: 95
Processing Batch id: 96
Processing Batch id: 97
Processing Batch id: 98
Processing Batch id: 99
Processing Batch id: 100
Processing Batch id: 101
Processing Batch id: 102
Processing Batch id: 103
Processing Batch id: 104
Processing Batch id: 105
Processing Batch id: 106
Processing Batch id: 107
Processing Batch id: 108
Processing Batch id: 109
Processing Batch id: 110
Processing Batch id: 111
Processing Batch id: 112
Processing Batch id: 113
Processing Batch id: 114
Processing Batch id: 115
Processing Batch id: 116
Processing Batch id: 117
Processing Batch id: 118
Processing Batch id: 119
Processing Batch id: 120
Processing Batch id: 121
Processing Batch id: 122
Processing Batch id: 123
Processing Batch id: 124
Processing Batch id: 125
Processing Batch id: 126
Processing Batch id: 127
Processing Batch id: 128
Processing Batch id: 129
Processing Batch id: 130
Processing Batch id: 131
Processing Batch id: 132
Processing Batch id: 133
Processing Batch id: 134
Processing Batch id: 135
Processing Batch id: 136
Processing Batch id: 137
Processing Batch id: 138
Processing Batch id: 139
Processing Batch id: 140
Processing Batch id: 141
Processing Batch id: 142
Processing Batch id: 143
Processing Batch id: 144
Processing Batch id: 145
Processing Batch id: 146
Processing Batch id: 147
Processing Batch id: 148
Processing Batch id: 149
Processing Batch id: 150
Processing Batch id: 151
Processing Batch id: 152
Processing Batch id: 153
Processing Batch id: 154
Processing Batch id: 155
Processing Batch id: 156
Processing Batch id: 157
Processing Batch id: 158
Processing Batch id: 159
Processing Batch id: 160
Processing Batch id: 161
Processing Batch id: 162
Processing Batch id: 163
Processing Batch id: 164
Processing Batch id: 165
Processing Batch id: 166
Processing Batch id: 167
Processing Batch id: 168
Processing Batch id: 169
Processing Batch id: 170
Processing Batch id: 171
Processing Batch id: 172
Processing Batch id: 173
Processing Batch id: 174
Processing Batch id: 175
Processing Batch id: 176
Processing Batch id: 177
Processing Batch id: 178
Processing Batch id: 179
Processing Batch id: 180
Processing Batch id: 181
Processing Batch id: 182
Processing Batch id: 183
Processing Batch id: 184
Processing Batch id: 185
Processing Batch id: 186
Processing Batch id: 187
Processing Batch id: 188
Processing Batch id: 189
Processing Batch id: 190
Processing Batch id: 191
Processing Batch id: 192
Processing Batch id: 193
Processing Batch id: 194
Processing Batch id: 195
Processing Batch id: 196
Processing Batch id: 197
Processing Batch id: 198
Processing Batch id: 199
Processing Batch id: 200
Processing Batch id: 201
Processing Batch id: 202
Processing Batch id: 203
Processing Batch id: 204
Processing Batch id: 205
Processing Batch id: 206
Processing Batch id: 207
Processing Batch id: 208
Processing Batch id: 209
Processing Batch id: 210
Processing Batch id: 211
Processing Batch id: 212
Processing Batch id: 213
Processing Batch id: 214
Processing Batch id: 215
Processing Batch id: 216
Processing Batch id: 217
Processing Batch id: 218
Processing Batch id: 219
Processing Batch id: 220
Processing Batch id: 221
Processing Batch id: 222
Processing Batch id: 223
Processing Batch id: 224
Processing Batch id: 225
Processing Batch id: 226
Processing Batch id: 227
Processing Batch id: 228
Processing Batch id: 229
Processing Batch id: 230
Processing Batch id: 231
Processing Batch id: 232
Processing Batch id: 233
Processing Batch id: 234
Processing Batch id: 235
Processing Batch id: 236
Processing Batch id: 237
Processing Batch id: 238
Processing Batch id: 239
Processing Batch id: 240
Processing Batch id: 241
Processing Batch id: 242
Processing Batch id: 243
Processing Batch id: 244
Processing Batch id: 245
Processing Batch id: 246
Processing Batch id: 247
Processing Batch id: 248
Processing Batch id: 249
Processing Batch id: 250
Processing Batch id: 251
Processing Batch id: 252
Processing Batch id: 253
Processing Batch id: 254
Processing Batch id: 255
Processing Batch id: 256
Processing Batch id: 257
Processing Batch id: 258
Processing Batch id: 259
Processing Batch id: 260
Processing Batch id: 261
Processing Batch id: 262
Processing Batch id: 263
Processing Batch id: 264
Processing Batch id: 265
Processing Batch id: 266
Processing Batch id: 267
Processing Batch id: 268
Processing Batch id: 269
Processing Batch id: 270
Processing Batch id: 271
Processing Batch id: 272
Processing Batch id: 273
Processing Batch id: 274
Processing Batch id: 275
Processing Batch id: 276
Processing Batch id: 277
Processing Batch id: 278
Processing Batch id: 279
Processing Batch id: 280
Processing Batch id: 281
Processing Batch id: 282
Processing Batch id: 283
Processing Batch id: 284
Processing Batch id: 285
Processing Batch id: 286
Processing Batch id: 287
Processing Batch id: 288
Processing Batch id: 289
Processing Batch id: 290
Processing Batch id: 291
Processing Batch id: 292
Processing Batch id: 293
Processing Batch id: 294
Processing Batch id: 295
Processing Batch id: 296
Processing Batch id: 297
Processing Batch id: 298
Processing Batch id: 299
Processing Batch id: 300
Processing Batch id: 301
Processing Batch id: 302
Processing Batch id: 303
Processing Batch id: 304
Processing Batch id: 305
Processing Batch id: 306
Processing Batch id: 307
Processing Batch id: 308
Processing Batch id: 309
Processing Batch id: 310
Processing Batch id: 311
Processing Batch id: 312
Processing Batch id: 313
Processing Batch id: 314
Processing Batch id: 315
Processing Batch id: 316
Processing Batch id: 317
Processing Batch id: 318
Processing Batch id: 319
Processing Batch id: 320
Processing Batch id: 321
Processing Batch id: 322
Processing Batch id: 323
Processing Batch id: 324
Processing Batch id: 325
Processing Batch id: 326
Processing Batch id: 327
Processing Batch id: 328
Processing Batch id: 329
Processing Batch id: 330
Processing Batch id: 331
Processing Batch id: 332
Processing Batch id: 333
Processing Batch id: 334
Processing Batch id: 335
Processing Batch id: 336
Processing Batch id: 337
Processing Batch id: 338
Processing Batch id: 339
Processing Batch id: 340
Processing Batch id: 341
Processing Batch id: 342
Processing Batch id: 343
Processing Batch id: 344
Processing Batch id: 345
Processing Batch id: 346
Processing Batch id: 347
Processing Batch id: 348
Processing Batch id: 349
Processing Batch id: 350
Processing Batch id: 351
Processing Batch id: 352
Processing Batch id: 353
Processing Batch id: 354
Processing Batch id: 355
Processing Batch id: 356
Processing Batch id: 357
Processing Batch id: 358
Processing Batch id: 359
Processing Batch id: 360
Processing Batch id: 361
Processing Batch id: 362
Processing Batch id: 363
Processing Batch id: 364
Processing Batch id: 365
Processing Batch id: 366
Processing Batch id: 367
Processing Batch id: 368
Processing Batch id: 369
Processing Batch id: 370
Processing Batch id: 371
Processing Batch id: 372
Processing Batch id: 373
Processing Batch id: 374
Processing Batch id: 375
Processing Batch id: 376
Processing Batch id: 377
Processing Batch id: 378
Processing Batch id: 379
Processing Batch id: 380
Processing Batch id: 381
Processing Batch id: 382
Processing Batch id: 383
Processing Batch id: 384
Processing Batch id: 385
Processing Batch id: 386
Processing Batch id: 387
Processing Batch id: 388
Processing Batch id: 389
Processing Batch id: 390
Processing Batch id: 391
Processing Batch id: 392
Processing Batch id: 393
Processing Batch id: 394
Processing Batch id: 395
Processing Batch id: 396
Processing Batch id: 397
Processing Batch id: 398
Processing Batch id: 399
Processing Batch id: 400
Processing Batch id: 401
Processing Batch id: 402
Processing Batch id: 403
Processing Batch id: 404
Processing Batch id: 405
Processing Batch id: 406
Processing Batch id: 407
Processing Batch id: 408
Processing Batch id: 409
Processing Batch id: 410
Processing Batch id: 411
Processing Batch id: 412
Processing Batch id: 413
Processing Batch id: 414
Processing Batch id: 415
Processing Batch id: 416
Processing Batch id: 417
Processing Batch id: 418
Processing Batch id: 419
Processing Batch id: 420
Processing Batch id: 421
Processing Batch id: 422
Processing Batch id: 423
Processing Batch id: 424
Processing Batch id: 425
Processing Batch id: 426
Processing Batch id: 427
Processing Batch id: 428
Processing Batch id: 429
Processing Batch id: 430
Processing Batch id: 431
Processing Batch id: 432
Processing Batch id: 433
Processing Batch id: 434
Processing Batch id: 435
Processing Batch id: 436
Processing Batch id: 437
Processing Batch id: 438
Processing Batch id: 439
Processing Batch id: 440
Processing Batch id: 441
Processing Batch id: 442
Processing Batch id: 443
Processing Batch id: 444
Processing Batch id: 445
Processing Batch id: 446
Processing Batch id: 447
Processing Batch id: 448
Processing Batch id: 449
Processing Batch id: 450
Processing Batch id: 451
Processing Batch id: 452
Processing Batch id: 453
Processing Batch id: 454
Processing Batch id: 455
Processing Batch id: 456
Processing Batch id: 457
Processing Batch id: 458
Processing Batch id: 459
Processing Batch id: 460
Processing Batch id: 461
Processing Batch id: 462
Processing Batch id: 463
Processing Batch id: 464
Processing Batch id: 465
Processing Batch id: 466
Processing Batch id: 467

In [ ]:
image_embedding_df = pd.DataFrame(rows)
image_embedding_df.shape

(7470, 3)

In [ ]:
image_embedding_df.head()

,uid,image_path,image_embedding
0,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032350257, -0.017342253, -0.016514145, -0...."
1,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03234609, -0.01733104, -0.01651474, -0.023..."
2,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343574, -0.017348982, -0.01651433, -0.0..."
3,1001,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03233781, -0.017337972, -0.016515464, -0.0..."
4,1001,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032333896, -0.017342517, -0.016514502, -0...."

In [ ]:
import pandas as pd

out_path = "/content/drive/MyDrive/comp-final-project/image_embeddings.pkl"
image_embedding_df.to_pickle(out_path)

print("Saved to:", out_path)

Saved to: /content/drive/MyDrive/comp-final-project/image_embeddings.pkl

### Creating FIASS External Knowledge Base

In [ ]:
import pandas as pd
import numpy as np
import joblib

In [ ]:
text_embeddings = pd.read_pickle('/content/drive/MyDrive/comp-final-project/report_text_embeddings_with_text.pkl')
text_embeddings

,uid,diagnosis,diagnosis_embeds
0,1,the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,2,borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,4,there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
4,5,the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
5,6,heart size and mediastinal contour are within ...,"[0.011237842, -0.02500179, 0.011986025, 0.0276..."
...,...,...,...
3844,3993,the heart is mildly enlarged. left hemidiaphra...,"[0.0071055642, -0.013249998, 0.018054985, 0.02..."
3845,3994,similar mild cardiomegaly. of the pulmonary va...,"[0.009199501, -0.022054106, 0.0049117906, 0.02..."
3846,3995,the cardiomediastinal silhouette and pulmonary...,"[0.009710249, -0.024965135, 0.0033454543, 0.03..."
3847,3996,the lungs are clear. heart size is normal. no ...,"[0.007932186, -0.027799036, 0.013058482, 0.020..."
3848,3997,"heart size within normal limits. small, nodula...","[0.020617524, -0.028144488, -0.0043227193, 0.0..."

In [ ]:
image_embeddings = pd.read_pickle('/content/drive/MyDrive/comp-final-project/image_embeddings.pkl')
image_embeddings

,uid,image_path,image_embedding
0,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032350257, -0.017342253, -0.016514145, -0...."
1,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03234609, -0.01733104, -0.01651474, -0.023..."
2,1000,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343574, -0.017348982, -0.01651433, -0.0..."
3,1001,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03233781, -0.017337972, -0.016515464, -0.0..."
4,1001,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032333896, -0.017342517, -0.016514502, -0...."
...,...,...,...
7465,999,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032346256, -0.017350404, -0.016516995, -0...."
7466,99,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032332774, -0.017344432, -0.016517023, -0...."
7467,99,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032341406, -0.017343592, -0.016516859, -0...."
7468,9,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343976, -0.017345933, -0.016515525, -0...."
7469,9,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032358203, -0.017346218, -0.016517852, -0...."

In [ ]:
image_embeddings = image_embeddings.sort_values(by='uid')
image_embeddings

,uid,image_path,image_embedding
2062,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032347087, -0.017341502, -0.016516779, -0...."
2063,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032351505, -0.01733234, -0.016519427, -0.0..."
4108,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235366, -0.017334813, -0.016517796, -0.0..."
4107,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032346543, -0.017334871, -0.016515227, -0...."
6219,3,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032367256, -0.01734567, -0.016518122, -0.0..."
...,...,...,...
6208,3997,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032354053, -0.017340837, -0.016519314, -0...."
6211,3998,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032359306, -0.017344983, -0.016518448, -0...."
6210,3998,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032346625, -0.01733743, -0.016515683, -0.0..."
6213,3999,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235547, -0.017342841, -0.016517077, -0.0..."
6212,3999,/content/drive/MyDrive/comp-final-project/ches...,"[-0.0323488, -0.017331006, -0.01651399, -0.023..."

In [ ]:
knowledge_base = image_embeddings.merge(text_embeddings, on='uid', how='left')

In [ ]:
knowledge_base.head(10)

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds
0,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032335542, -0.017344262, -0.0165142, -0.02...",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032338787, -0.017339641, -0.016515644, -0....",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
2,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03233849, -0.017340628, -0.01651468, -0.02...",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03233616, -0.017342292, -0.016513858, -0.0...",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
4,3,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032345135, -0.017345738, -0.016514694, -0....",NaN,NaN
5,3,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032341827, -0.017343711, -0.016514787, -0....",NaN,NaN
6,4,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032345567, -0.017342234, -0.016514223, -0....",there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
7,4,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032331705, -0.017350774, -0.016513012, -0....",there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
8,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235035, -0.017345406, -0.01651347, -0.02...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
9,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032342456, -0.017346917, -0.01651364, -0.0...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."

In [ ]:
knowledge_base = knowledge_base.dropna(subset=['diagnosis_embeds'])
knowledge_base.head(10)

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds
0,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032347087, -0.017341502, -0.016516779, -0....",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032351505, -0.01733234, -0.016519427, -0.0...",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
2,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235366, -0.017334813, -0.016517796, -0.0...",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032346543, -0.017334871, -0.016515227, -0....",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
6,4,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032364678, -0.017336959, -0.016516583, -0....",there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
7,4,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032335296, -0.017353727, -0.016513698, -0....",there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."
8,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03237251, -0.017341034, -0.016514553, -0.0...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
9,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235772, -0.017345995, -0.01651532, -0.02...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
10,6,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032349907, -0.017346527, -0.016517589, -0....",heart size and mediastinal contour are within ...,"[0.011237842, -0.02500179, 0.011986025, 0.0276..."
11,6,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03234587, -0.017346399, -0.01651461, -0.02...",heart size and mediastinal contour are within ...,"[0.011237842, -0.02500179, 0.011986025, 0.0276..."

In [ ]:
knowledge_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6461 entries, 0 to 7465
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uid               6461 non-null   int64
 1   image_path        6461 non-null   object
 2   image_embedding   6461 non-null   object
 3   diagnosis         6461 non-null   object
 4   diagnosis_embeds  6461 non-null   object
dtypes: int64(1), object(4)
memory usage: 302.9+ KB

In [ ]:
knowledge_base.shape

(6461, 5)

### Saving knowledge base

In [ ]:
out_path = "/content/drive/MyDrive/comp-final-project/knowledge_base_embeddings.pkl"
knowledge_base.to_pickle(out_path)

print(f'Knowledge Base EMbeddings saved to: {out_path}')

Knowledge Base EMbeddings saved to: /content/drive/MyDrive/comp-final-project/knowledge_base_embeddings.pkl

### FAISS Index from Knowledge Base

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 33.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [ ]:
import pandas as pd
import numpy as np
import faiss

In [ ]:
knowledge_base = pd.read_pickle('/content/drive/MyDrive/comp-final-project/knowledge_base_embeddings.pkl')
knowledge_base = knowledge_base.reset_index(drop=True).copy()
knowledge_base.head()

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds
0,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032351505, -0.01733234, -0.016519427, -0.0...",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032347087, -0.017341502, -0.016516779, -0....",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
2,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032346543, -0.017334871, -0.016515227, -0....",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
3,2,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235366, -0.017334813, -0.016517796, -0.0...",borderline cardiomegaly. midline sternotomy . ...,"[0.011446322, -0.016496917, 0.004618658, 0.021..."
4,4,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032364678, -0.017336959, -0.016516583, -0....",there are diffuse bilateral interstitial and a...,"[0.016286246, -0.035288382, -0.0017745462, 0.0..."

In [ ]:
# splitting the knowledge base for separating test cases
uids = knowledge_base['uid'].unique()
print(f'Total Cases: {len(uids)}')

np.random.seed(11)
np.random.shuffle(uids)

split_ratio = 0.8
split_idx = int(len(uids) * split_ratio)

knowledge_case_ids = set(uids[:split_idx])
test_case_ids = set(uids[split_idx:])

Total Cases: 3331

In [ ]:
knowledge_cases = knowledge_base[knowledge_base['uid'].isin(knowledge_case_ids)].reset_index(drop=True)
test_cases = knowledge_base[knowledge_base['uid'].isin(test_case_ids)].reset_index(drop=True)

print(f'Knowledge cases: {len(knowledge_cases)}')
print(f'Test cases: {len(test_cases)}')
print(f'Case ids in knowledge_base: {knowledge_cases['uid'].nunique()}')
print(f'Case ids in test base: {test_cases['uid'].nunique()}')

Knowledge cases: 5173
Test cases: 1288
Case ids in knowledge_base: 2664
Case ids in test base: 667

In [ ]:
out_path = '/content/drive/MyDrive/comp-final-project/test_cases_knowledge_base_embeddings.pkl'
test_cases.to_pickle(out_path)

In [ ]:
image_embeds = knowledge_cases['image_embedding']
image_embeds.shape

(5173,)

In [ ]:
img_embed_stack = np.stack(image_embeds.values)
img_embed_stack = img_embed_stack.astype('float32')

In [ ]:
faiss.normalize_L2(img_embed_stack)

In [ ]:
dims = img_embed_stack.shape[1]
image_embeds_index = faiss.IndexFlatIP(dims)
image_embeds_index.add(img_embed_stack)

print(f'Image Embedding Vector Index Created')
print(f'Total Vectors: {image_embeds_index.ntotal}')

Image Embedding Vector Index Created
Total Vectors: 5173

In [ ]:
print("img_embed_stack.shape:", img_embed_stack.shape)
print("dtype:", img_embed_stack.dtype)
print("contiguous:", img_embed_stack.flags['C_CONTIGUOUS'])
print("dims used:", dims)

img_embed_stack.shape: (5173, 1024)
dtype: float32
contiguous: True
dims used: 1024

In [ ]:
out_path = '/content/drive/MyDrive/comp-final-project/chest_xray_kb.index'
faiss.write_index(image_embeds_index,out_path)

### Building Retrieval System

In [ ]:
import numpy as np
import faiss
import pandas as pd

In [ ]:
image_embeds_index = faiss.read_index('/content/drive/MyDrive/comp-final-project/chest_xray_kb.index')

In [ ]:
test_cases = pd.read_pickle('/content/drive/MyDrive/comp-final-project/test_cases_knowledge_base_embeddings.pkl')

In [ ]:
'''
Given an X-ray embedding,
retrieve visually similar past images and return their metadata.
'''


def retrieve_similar_cases(query_image,
                           knowledge_base =knowledge_cases,
                           faiss_index =image_embeds_index,
                           N=20):

  search_qry = np.asarray(query_image, dtype='float32').reshape(1,-1)
  faiss.normalize_L2(search_qry)

  scores, indices = faiss_index.search(search_qry, N)

  retrieved_cases = knowledge_base.iloc[indices[0]].copy()
  retrieved_cases['sim_score'] = scores[0]

  return retrieved_cases

In [ ]:
test_cases.head()

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds
0,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032351505, -0.01733234, -0.016519427, -0.0...",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
1,1,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032347087, -0.017341502, -0.016516779, -0....",the cardiac silhouette and mediastinum size ar...,"[0.006966598, -0.014430174, 0.01299472, 0.0229..."
2,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235772, -0.017345995, -0.01651532, -0.02...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
3,5,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03237251, -0.017341034, -0.016514553, -0.0...",the cardiomediastinal silhouette and pulmonary...,"[0.012669654, -0.026295086, 0.0033105828, 0.03..."
4,9,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343976, -0.017345933, -0.016515525, -0....",the examination consists of frontal and latera...,"[0.009908557, -0.023219962, -0.011978911, 0.00..."

In [ ]:
test = test_cases.sample()
test

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds
995,3174,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235651, -0.017347362, -0.016515864, -0.0...",the lungs are hyperinflated with biapical pleu...,"[0.0029751675, -0.032782093, 0.0021822825, 0.0..."

In [ ]:
test['image_embedding'].values[0].shape

(1024,)

In [ ]:
test_sim_cases = retrieve_similar_cases(test['image_embedding'].values[0])

In [ ]:
test_sim_cases

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds,sim_score
1420,1089,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03236286, -0.017334882, -0.016517766, -0.0...",the heart size and pulmonary vascularity appea...,"[0.0007785495, -0.018491786, 0.005248113, 0.02...",1.0
1344,1032,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03234756, -0.017343542, -0.016515287, -0.0...",the cardiomediastinal silhouette and pulmonary...,"[0.01279772, -0.020599846, -0.0010487498, 0.02...",1.0
1309,1007,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235566, -0.017341843, -0.016517024, -0.0...",trachea is midline. the cardiomediastinal silh...,"[0.0057915496, -0.029983122, 0.012221354, 0.02...",1.0
1291,991,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032359734, -0.017342934, -0.01651766, -0.0...",the heart size is upper limits of normal. the ...,"[0.0027914308, -0.028474558, 0.0076784063, 0.0...",1.0
1287,989,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032352902, -0.017347198, -0.016515192, -0....",the cardiac contours are normal. the lungs are...,"[0.0150430845, -0.014607525, -0.00033705943, 0...",1.0
1211,937,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032349527, -0.017347483, -0.016517352, -0....",normal cardiac size. normal pulmonary vasculat...,"[0.0051384293, -0.022376982, 0.008245162, 0.01...",1.0
1027,793,/content/drive/MyDrive/comp-final-project/ches...,"[-0.0323469, -0.017348917, -0.016515458, -0.02...",the examination consists of frontal and latera...,"[0.0067681074, -0.03346838, 0.0042065615, 0.02...",1.0
930,723,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032340206, -0.017346164, -0.01651538, -0.0...","the heart, pulmonary and mediastinum are withi...","[0.0007170391, -0.027946414, -0.0033180127, 0....",1.0
839,655,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343745, -0.017344007, -0.016517656, -0....",normal heart size and mediastinal contours. th...,"[0.007818653, -0.022082968, 0.011529691, 0.032...",1.0
802,628,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032362446, -0.017354043, -0.01651611, -0.0...",frontal and lateral views of the chest with ov...,"[0.013185857, -0.021943243, -0.0001531324, 0.0...",1.0
730,565,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032351684, -0.017340962, -0.016517004, -0....","the lungs are clear bilaterally. specifically,...","[0.010366997, -0.028367925, 0.01643863, 0.0201...",1.0
597,457,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032356177, -0.017344328, -0.016517596, -0....",there is a calcified granuloma left midlung. t...,"[0.011152011, -0.045444805, -0.021447128, 0.02...",1.0
493,377,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032350518, -0.0173378, -0.01651726, -0.023...",heart size and pulmonary vascularity appear wi...,"[0.010645065, -0.034700602, 0.015558859, 0.031...",1.0
365,287,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032347653, -0.017343068, -0.016516179, -0....",heart size is normal. the lungs are grossly cl...,"[0.013157587, -0.021205503, 0.016586073, 0.032...",1.0
311,242,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032357715, -0.017345078, -0.016517272, -0....",lungs are clear bilaterally with no focal infi...,"[0.012467133, -0.026596379, 0.018749587, 0.028...",1.0
288,224,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03233485, -0.017347699, -0.016513668, -0.0...",clear lungs. normal heart. no pneumothorax. no...,"[0.012051746, -0.021984715, 0.014170757, 0.024...",1.0
233,182,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032343794, -0.01734817, -0.016513903, -0.0...",heart size and mediastinal contours appear wit...,"[0.025815818, -0.027774908, 0.0066470033, 0.02...",1.0
174,130,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032364782, -0.017333277, -0.016517915, -0....",the lungs are clear. heart size is normal. no ...,"[0.010010101, -0.022665203, 0.003547772, 0.017...",1.0
49,39,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032348815, -0.017341368, -0.016516425, -0....",the heart and lungs have in the interval. both...,"[0.014380161, -0.025812723, 0.004359888, 0.025...",1.0
42,36,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032355152, -0.017333947, -0.016516656, -0....","the lungs are clear bilaterally. specifically,...","[0.010366997, -0.028367925, 0.01643863, 0.0201...",1.0

In [ ]:
sim_cases_test = {}

### Building Re Ranker

In [ ]:
import numpy as np

def l2_normalization(X, eps=1e-12):
    X = np.asarray(X, dtype=np.float32)
    if X.ndim == 1:
        return X / (np.linalg.norm(X) + eps)
    return X / (np.linalg.norm(X, axis=1, keepdims=True) + eps)

In [ ]:
# Consensus clustering
from sklearn.cluster import AgglomerativeClustering

def rerank_retrieved_embeds(retrieved_cases,
                       text_embed_col = 'diagnosis_embeds',
                       top_k = 5,
                       min_cluster_size = 3,
                       dist_threshold = 0.03):

  embeds = np.vstack(retrieved_cases[text_embed_col].values).astype('float32')
  embeds = l2_normalization(embeds)

  cos_sim = embeds @ embeds.T
  distance = 1.0 - cos_sim
  np.fill_diagonal(distance, 0.0)

  clustering = AgglomerativeClustering(
        metric="precomputed",
        linkage="average",
        distance_threshold=dist_threshold,
        n_clusters=None
    )

  labels = clustering.fit_predict(distance)

  result = retrieved_cases.copy()
  result['cluster'] = labels

  result['intra_clust_sim'] = cos_sim.mean(axis=1)

  cluster_stats = (
        result.groupby("cluster")
           .agg(
               size=("cluster", "size"),
               avg_intra=("intra_clust_sim", "mean")
           )
           .sort_values(["size", "avg_intra"], ascending=False)
    )

  #Fallback if clustering fragments too much
  if cluster_stats.iloc[0]["size"] < min_cluster_size:
        print('Clustering fragment too much, falling back to img score')
        return (
            result.sort_values("sim_score", ascending=False)
               .head(top_k)
               .reset_index(drop=True),
            cluster_stats
        )

  best_cluster = cluster_stats.index[0]

  best = (
        result[result["cluster"] == best_cluster]
        .sort_values("intra_clust_sim", ascending=False)
        .head(top_k)
        .reset_index(drop=True)
    )

  return best, cluster_stats

In [ ]:
consistent_cases, cluster_stats = rerank_retrieved_embeds(test_sim_cases)
print(cluster_stats)

         size  avg_intra
cluster
1           7   0.965037
0           4   0.962774
2           2   0.958893
6           2   0.954290
7           1   0.958690
5           1   0.957510
8           1   0.957429
4           1   0.954635
3           1   0.920923

In [ ]:
consistent_cases

,uid,image_path,image_embedding,diagnosis,diagnosis_embeds,sim_score,cluster,intra_clust_sim
0,542,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03235882, -0.017332284, -0.016518904, -0.0...",trachea is midline. the cardiomediastinal silh...,"[0.005986236, -0.025366098, 0.00951613, 0.0239...",1.0,1,0.967679
1,991,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032359734, -0.017342934, -0.01651766, -0.0...",the heart size is upper limits of normal. the ...,"[0.0027914308, -0.028474558, 0.0076784063, 0.0...",1.0,1,0.966623
2,1671,/content/drive/MyDrive/comp-final-project/ches...,"[-0.032371446, -0.017335568, -0.016518446, -0....",heart size and mediastinal contours are within...,"[0.018188315, -0.021059804, 0.014304522, 0.030...",1.0,1,0.966264
3,1364,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03234764, -0.01733075, -0.016518023, -0.02...",the cardiomediastinal silhouette and pulmonary...,"[0.007878558, -0.023355251, 0.012659243, 0.028...",1.0,1,0.966080
4,621,/content/drive/MyDrive/comp-final-project/ches...,"[-0.03236017, -0.0173363, -0.016518792, -0.023...","the heart, pulmonary and mediastinum are withi...","[0.0056317146, -0.020746496, 0.020144656, 0.03...",1.0,1,0.964001

In [ ]:
# saving test sample
out_path = '/content/drive/MyDrive/comp-final-project/retrievd_test_case.pkl'
consistent_cases.to_pickle(out_path)

### Input For LLM

In [ ]:
import pandas as pd

In [ ]:
out_path = '/content/drive/MyDrive/comp-final-project/retrievd_test_case.pkl'
consistent_cases = pd.read_pickle(out_path)

ModuleNotFoundError: No module named 'numpy._core.numeric'

In [ ]:
diagnosis_texts = consistent_cases['diagnosis'].tolist()
diagnosis_texts

NameError: name 'consistent_cases' is not defined

In [ ]:
grounded_truth = []
for i, text in enumerate(diagnosis_texts):
  row = f'case {i+1}: {text}'
  grounded_truth.append(row)

grounded_truth

NameError: name 'diagnosis_texts' is not defined

In [ ]:
grounded_truth = ['case 1: trachea is midline. the cardiomediastinal silhouette is normal. the lungs are clear without evidence of acute infiltrate or effusion. there is no pneumothorax. the visualized bony structures reveal no acute abnormality. no acute cardiopulmonary abnormality.',
 'case 2: the heart size is upper limits of normal. the pulmonary and mediastinum are within normal limits. there is no pleural effusion or pneumothorax. there is mild streaky perihilar opacity without confluent airspace opacity to suggest a bacterial pneumonia. minimal perihilar opacity which could indicate an atypical pneumonia.',
 'case 3: heart size and mediastinal contours are within normal limits. there is no pneumothorax, pleural effusion, focal airspace consolidation. no acute cardiopulmonary findings.',
 'case 4: the cardiomediastinal silhouette and pulmonary vasculature are within normal limits in size. the lungs are clear of focal airspace disease, pneumothorax, or pleural effusion. there are no acute bony findings. no acute cardiopulmonary findings.',
 'case 5: the heart, pulmonary and mediastinum are within normal limits. there is no pleural effusion or pneumothorax. there is no focal air space opacity to suggest a pneumonia. there are mild degenerative changes of the spine. no acute cardiopulmonary disease.']

### LLM Setup

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.16.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.2)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [ ]:
from google.colab import userdata
import os
from openai import OpenAI

In [ ]:
client = OpenAI(api_key = userdata.get('OPENAI_API_KEY'))

In [ ]:
resp = client.responses.create(
    model = 'gpt-5.1',
    input = 'Hi, tell me a popular proverb'
)

In [ ]:
print(resp.output_text)

“A journey of a thousand miles begins with a single step.”

In [ ]:
# System Prompts
system_instruction = (
    "You are a clinical assistant for summarizing chest X-ray evidence.\n"
    "You must use ONLY the evidence provided.\n"
    "Never introduce a finding that is not mentioned in the evidence set\n"
    "Do not add findings not present in the evidence.\n"
    "Return JSON only."
)

In [ ]:
system_instruction_v2 = (
    "You are a radiologist writing the IMPRESSION section for a chest X-ray report.\n"
    "Write in standard radiology style: concise, objective, clinically focused.\n"
    "Use ONLY the provided evidence. Do NOT add any new findings.\n"
    "Do NOT state a finding is absent (e.g., 'no effusion') unless the evidence explicitly states it.\n"
    "If the evidence is insufficient to conclude a finding, omit it or state 'indeterminate' (only if evidence suggests uncertainty).\n"
    "Prefer short sentences and common radiology terms (e.g., 'No acute cardiopulmonary abnormality', 'Cardiomediastinal silhouette').\n"
    "Return VALID JSON ONLY. No extra text."
)

In [ ]:
# User Evidence
user_task = f"""
Retrieved evidence:
{grounded_truth}

Task:
Question:
Generate impression for the given case based only on this evidence?
Return a JSON object with keys:
- impression: string
- reasoning: string (cite phrases from evidence)
- confidence: one of ['High','Medium','Low']
- outlier_note: string (or '' if none)
""".strip()

In [ ]:
def create_prompt(grounded_truth):
  user_task_v2= f"""
Retrieved evidence:
{grounded_truth}

Task:
Question:
Generate impression for the given case based only on this evidence?
OUTPUT JSON SCHEMA:
{{
  "impression": "1-3 sentences. Radiology impression style. No bullets unless multiple key findings. List 1-3 short quoted phrases copied EXACTLY from EVIDENCE that justify the impression"
  "confidence": "High|Medium|Low",
  "outlier_note": "If evidence contains conflicting/rare finding, describe briefly; else ''"
}}

RULES:
- Do not mention diagnoses/findings not explicitly supported by EVIDENCE.
- Do not generalize from other cases (no 'most cases show...'). Treat EVIDENCE as the only source for this case.
- If EVIDENCE contains both positive and negative statements for a finding, mention the conflict in outlier_note and lower confidence.
""".strip()
  return [
      {
          'role':'system',
          'content': system_instruction_v2
      },
      {
          'role':'user',
          'content': user_task_v2
      }
  ]

In [ ]:
def call_llm_api(input_prompt):
  model = 'gpt-5.1'
  response = client.responses.create(
    model = model,
    input = input_prompt,
    temperature=0.0,
    max_output_tokens=512
    )

  return response.output_text

### Calling LLM API

In [ ]:
input_prompt = create_prompt(grounded_truth)

api_response = call_llm_api(input_prompt)

In [ ]:
print(f'Response from API : {api_response}')

Response from API : {
  "impression": "No acute cardiopulmonary abnormality. Normal cardiomediastinal silhouette and clear lungs without evidence of acute infiltrate, effusion, or pneumothorax. Visualized bony structures show no acute abnormality.",
  "confidence": "High",
  "outlier_note": "",
  "evidence_quotes": [
    "the cardiomediastinal silhouette is normal",
    "the lungs are clear without evidence of acute infiltrate or effusion. there is no pneumothorax",
    "the visualized bony structures reveal no acute abnormality. no acute cardiopulmonary abnormality."
  ]
}

In [ ]:
test_results = []

In [ ]:
count =0
for _, record in test_cases.iterrows():
  test_run = {}
  img_embed = record['image_embedding']
  sim_cases = retrieve_similar_cases(img_embed)
  consistent_cases, cluster_stats = rerank_retrieved_embeds(sim_cases)
  diagnosis_texts = consistent_cases['diagnosis'].tolist()

  grounded_truth = []
  for i, text in enumerate(diagnosis_texts):
    row = f'case {i+1}: {text}'
    grounded_truth.append(row)

  input_prompt = create_prompt(grounded_truth)
  api_response = call_llm_api(input_prompt)

  test_run['case_id'] = int(record['uid'])
  test_run['diagnosis'] = record['diagnosis']
  test_run['evidence_set'] = grounded_truth
  test_run['gen_report'] = api_response

  count = count + 1
  print(f'{count}: records processed')

  test_results.append(test_run)

1: records processed
2: records processed
3: records processed
4: records processed
5: records processed
6: records processed
7: records processed
8: records processed
9: records processed
10: records processed
11: records processed
12: records processed
13: records processed
14: records processed
15: records processed
16: records processed
17: records processed
18: records processed
19: records processed
20: records processed
21: records processed
22: records processed
23: records processed
24: records processed
25: records processed
26: records processed
27: records processed
28: records processed
29: records processed
30: records processed
31: records processed
32: records processed
33: records processed
34: records processed
35: records processed
36: records processed
37: records processed
38: records processed
39: records processed
40: records processed
41: records processed
42: records processed
43: records processed
44: records processed
45: records processed
46: records processed
47: records processed
48: records processed
49: records processed
50: records processed
51: records processed
52: records processed
53: records processed
54: records processed
55: records processed
56: records processed
57: records processed
58: records processed
59: records processed
60: records processed
61: records processed
62: records processed
63: records processed
64: records processed
65: records processed
66: records processed
67: records processed
68: records processed
69: records processed
70: records processed
71: records processed
72: records processed
73: records processed
74: records processed
75: records processed
76: records processed
77: records processed
78: records processed
79: records processed
80: records processed
81: records processed
82: records processed
83: records processed
84: records processed
85: records processed
86: records processed
87: records processed
88: records processed
89: records processed
90: records processed
91: records processed
92: records processed
93: records processed
94: records processed
95: records processed
96: records processed
97: records processed
98: records processed
99: records processed
100: records processed
101: records processed
102: records processed
103: records processed
104: records processed
105: records processed
106: records processed
107: records processed
108: records processed
109: records processed
110: records processed
111: records processed
112: records processed
113: records processed
114: records processed
115: records processed
116: records processed
117: records processed
118: records processed
119: records processed
120: records processed
121: records processed
122: records processed
123: records processed
124: records processed
125: records processed
126: records processed
127: records processed
128: records processed
129: records processed
130: records processed
131: records processed
132: records processed
133: records processed
134: records processed
135: records processed
136: records processed
137: records processed
138: records processed
139: records processed
140: records processed
141: records processed
142: records processed
143: records processed
144: records processed
145: records processed
146: records processed
147: records processed
148: records processed
149: records processed
150: records processed
151: records processed
152: records processed
153: records processed
154: records processed
155: records processed
156: records processed
157: records processed
158: records processed
159: records processed
160: records processed
161: records processed
162: records processed
163: records processed
164: records processed
165: records processed
166: records processed
167: records processed
168: records processed
169: records processed
170: records processed
171: records processed
172: records processed
173: records processed
174: records processed
175: records processed
176: records processed
177: records processed
178: records processed
179: records processed
180: records processed
181: records processed
182: records processed
183: records processed
184: records processed
185: records processed
186: records processed
187: records processed
188: records processed
189: records processed
190: records processed
191: records processed
192: records processed
193: records processed
194: records processed
195: records processed
196: records processed
197: records processed
198: records processed
199: records processed
200: records processed
201: records processed
202: records processed
203: records processed
204: records processed
205: records processed
206: records processed
207: records processed
208: records processed
209: records processed
210: records processed
211: records processed
212: records processed
213: records processed
214: records processed
215: records processed
216: records processed
217: records processed
218: records processed
219: records processed
220: records processed
221: records processed
222: records processed
223: records processed
224: records processed
225: records processed
226: records processed
227: records processed
228: records processed
229: records processed
230: records processed
231: records processed
232: records processed
233: records processed
234: records processed
235: records processed
236: records processed
237: records processed
238: records processed
239: records processed
240: records processed
241: records processed
242: records processed
243: records processed
244: records processed
245: records processed
246: records processed
247: records processed
248: records processed
249: records processed
250: records processed
251: records processed
252: records processed
253: records processed
254: records processed
255: records processed
256: records processed
257: records processed
258: records processed
259: records processed
260: records processed
261: records processed
262: records processed
263: records processed
264: records processed
265: records processed
266: records processed
267: records processed
268: records processed
269: records processed
270: records processed
271: records processed
272: records processed
273: records processed
274: records processed
275: records processed
276: records processed
277: records processed
278: records processed
279: records processed
280: records processed
281: records processed
282: records processed
283: records processed
284: records processed
285: records processed
286: records processed
287: records processed
288: records processed
289: records processed
290: records processed
291: records processed
292: records processed
293: records processed
294: records processed
295: records processed
296: records processed
297: records processed
298: records processed
299: records processed
300: records processed
301: records processed
302: records processed
303: records processed
304: records processed
305: records processed
306: records processed
307: records processed
308: records processed
309: records processed
310: records processed
311: records processed
312: records processed
313: records processed
314: records processed
315: records processed
316: records processed
317: records processed
318: records processed
319: records processed
320: records processed
321: records processed
322: records processed
323: records processed
324: records processed
325: records processed
326: records processed
327: records processed
328: records processed
329: records processed
330: records processed
331: records processed
332: records processed
333: records processed
334: records processed
335: records processed
336: records processed
337: records processed
338: records processed
339: records processed
340: records processed
341: records processed
342: records processed
343: records processed
344: records processed
345: records processed
346: records processed
347: records processed
348: records processed
349: records processed
350: records processed
351: records processed
352: records processed
353: records processed
354: records processed
355: records processed
356: records processed
357: records processed
358: records processed
359: records processed
360: records processed
361: records processed
362: records processed
363: records processed
364: records processed
365: records processed
366: records processed
367: records processed
368: records processed
369: records processed
370: records processed
371: records processed
372: records processed
373: records processed
374: records processed
375: records processed
376: records processed
377: records processed
378: records processed
379: records processed
380: records processed
381: records processed
382: records processed
383: records processed
384: records processed
385: records processed
386: records processed
387: records processed
388: records processed
389: records processed
390: records processed
391: records processed
392: records processed
393: records processed
394: records processed
395: records processed
396: records processed
397: records processed
398: records processed
399: records processed
400: records processed
401: records processed
402: records processed
403: records processed
404: records processed
405: records processed
406: records processed
407: records processed
408: records processed
409: records processed
410: records processed
411: records processed
412: records processed
413: records processed
414: records processed
415: records processed
416: records processed
417: records processed
418: records processed
419: records processed
420: records processed
421: records processed
422: records processed
423: records processed
424: records processed
425: records processed
426: records processed
427: records processed
428: records processed
429: records processed
430: records processed
431: records processed
432: records processed
433: records processed
434: records processed
435: records processed
436: records processed
437: records processed
438: records processed
439: records processed
440: records processed
441: records processed
442: records processed
443: records processed
444: records processed
445: records processed
446: records processed
447: records processed
448: records processed
449: records processed
450: records processed
451: records processed
452: records processed
453: records processed
454: records processed
455: records processed
456: records processed
457: records processed
458: records processed
459: records processed
460: records processed
461: records processed
462: records processed
463: records processed
464: records processed
465: records processed
466: records processed
467: records processed
468: records processed
469: records processed
470: records processed
471: records processed
472: records processed
473: records processed
474: records processed
475: records processed
476: records processed
477: records processed
478: records processed
479: records processed
480: records processed
481: records processed
482: records processed
483: records processed
484: records processed
485: records processed
486: records processed
487: records processed
488: records processed
489: records processed
490: records processed
491: records processed
492: records processed
493: records processed
494: records processed
495: records processed
496: records processed
497: records processed
498: records processed
499: records processed
500: records processed
501: records processed
502: records processed
503: records processed
504: records processed
505: records processed
506: records processed
507: records processed
508: records processed
509: records processed
510: records processed
511: records processed
512: records processed
513: records processed
514: records processed
515: records processed
516: records processed
517: records processed
518: records processed
519: records processed
520: records processed
521: records processed
522: records processed
523: records processed
524: records processed
525: records processed
526: records processed
527: records processed
528: records processed
529: records processed
530: records processed
531: records processed
532: records processed
533: records processed
534: records processed
535: records processed
536: records processed
537: records processed
538: records processed
539: records processed
540: records processed
541: records processed
542: records processed
543: records processed
544: records processed
545: records processed
546: records processed
547: records processed
548: records processed
549: records processed
550: records processed
551: records processed
552: records processed
553: records processed
554: records processed
555: records processed
556: records processed
557: records processed
558: records processed
559: records processed
560: records processed
561: records processed
562: records processed
563: records processed
564: records processed
565: records processed
566: records processed
567: records processed
568: records processed
569: records processed
570: records processed
571: records processed
572: records processed
573: records processed
574: records processed
575: records processed
576: records processed
577: records processed
578: records processed
579: records processed
580: records processed
581: records processed
582: records processed
583: records processed
584: records processed
585: records processed
586: records processed
587: records processed
588: records processed
589: records processed
590: records processed
591: records processed
592: records processed
593: records processed
594: records processed
595: records processed
596: records processed
597: records processed
598: records processed
599: records processed
600: records processed
601: records processed
602: records processed
603: records processed
604: records processed
605: records processed
606: records processed
607: records processed
608: records processed
609: records processed
610: records processed
611: records processed
612: records processed
613: records processed
614: records processed
615: records processed
616: records processed
617: records processed
618: records processed
619: records processed
620: records processed
621: records processed
622: records processed
623: records processed
624: records processed
625: records processed
626: records processed
627: records processed
628: records processed
629: records processed
630: records processed
631: records processed
632: records processed
633: records processed
634: records processed
635: records processed
636: records processed
637: records processed
638: records processed
639: records processed
640: records processed
641: records processed
642: records processed
643: records processed
644: records processed
645: records processed
646: records processed
647: records processed
648: records processed
649: records processed
650: records processed
651: records processed
652: records processed
653: records processed
654: records processed
655: records processed
656: records processed
657: records processed
658: records processed
659: records processed
660: records processed
661: records processed
662: records processed
663: records processed
664: records processed
665: records processed
666: records processed
667: records processed
668: records processed
669: records processed
670: records processed
671: records processed
672: records processed
673: records processed
674: records processed
675: records processed
676: records processed
677: records processed
678: records processed
679: records processed
680: records processed
681: records processed
682: records processed
683: records processed
684: records processed
685: records processed
686: records processed
687: records processed
688: records processed
689: records processed
690: records processed
691: records processed
692: records processed
693: records processed
694: records processed
695: records processed
696: records processed
697: records processed
698: records processed
699: records processed
700: records processed
701: records processed
702: records processed
703: records processed
704: records processed
705: records processed
706: records processed
707: records processed
708: records processed
709: records processed
710: records processed
711: records processed
712: records processed
713: records processed
714: records processed
715: records processed
716: records processed
717: records processed
718: records processed
719: records processed
720: records processed
721: records processed
722: records processed
723: records processed
724: records processed
725: records processed
726: records processed
727: records processed
728: records processed
729: records processed
730: records processed
731: records processed
732: records processed
733: records processed
734: records processed
735: records processed
736: records processed
737: records processed
738: records processed
739: records processed
740: records processed
741: records processed
742: records processed
743: records processed
744: records processed
745: records processed
746: records processed
747: records processed
748: records processed
749: records processed
750: records processed
751: records processed
752: records processed
753: records processed
754: records processed
755: records processed
756: records processed
757: records processed
758: records processed
759: records processed
760: records processed
761: records processed
762: records processed
763: records processed
764: records processed
765: records processed
766: records processed
767: records processed
768: records processed
769: records processed
770: records processed
771: records processed
772: records processed
773: records processed
774: records processed
775: records processed
776: records processed
777: records processed
778: records processed
779: records processed
780: records processed
781: records processed
782: records processed
783: records processed
784: records processed
785: records processed
786: records processed
787: records processed
788: records processed
789: records processed
790: records processed
791: records processed
792: records processed
793: records processed
794: records processed
795: records processed
796: records processed
797: records processed
798: records processed
799: records processed
800: records processed
801: records processed
802: records processed
803: records processed
804: records processed
805: records processed
806: records processed
807: records processed
808: records processed
809: records processed
810: records processed
811: records processed
812: records processed
813: records processed
814: records processed
815: records processed
816: records processed
817: records processed
818: records processed
819: records processed
820: records processed
821: records processed
822: records processed
823: records processed
824: records processed
825: records processed
826: records processed
827: records processed
828: records processed
829: records processed
830: records processed
831: records processed
832: records processed
833: records processed
834: records processed
835: records processed
836: records processed
837: records processed
838: records processed
839: records processed
840: records processed
841: records processed
842: records processed
843: records processed
844: records processed
845: records processed
846: records processed
847: records processed
848: records processed
849: records processed
850: records processed
851: records processed
852: records processed
853: records processed
854: records processed
855: records processed
856: records processed
857: records processed
858: records processed
859: records processed
860: records processed
861: records processed
862: records processed
863: records processed
864: records processed
865: records processed
866: records processed
867: records processed
868: records processed
869: records processed
870: records processed
871: records processed
872: records processed
873: records processed
874: records processed

In [ ]:
len(test_results)

1288

In [ ]:
import pickle
pickle.dump(test_results, open('/content/drive/MyDrive/comp-final-project/test_results_v3.pkl','wb'))

### Evaluation

In [ ]:
!pip install -U spacy scispacy medspacy negspacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Collecting scispacy
  Downloading scispacy-0.6.2-py3-none-any.whl.metadata (20 kB)
Collecting medspacy
  Downloading medspacy-1.3.1.tar.gz (244 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.6/244.6 kB 5.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting negspacy
  Downloading negspacy-1.0.4.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.16.3)
Collecting conllu (from scispacy)
  Downloading conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy>=1.19.0 (from spacy)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.5.3)
Collecting nmslib-metabrainz==2.1.3 (from scispacy)
  Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (956 bytes)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.6.1)
Collecting pysbd (from scispacy)
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting pybind11>=2.2.3 (from nmslib-metabrainz==2.1.3->scispacy)
  Downloading pybind11-3.0.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from nmslib-metabrainz==2.1.3->scispacy) (5.9.5)
Collecting PyRuSH>=1.0.8 (from medspacy)
  Downloading pyrush-1.0.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from medspacy) (4.26.0)
Collecting medspacy_quickumls==3.2 (from medspacy)
  Downloading medspacy_quickumls-3.2.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.9/69.9 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting unidecode>=0.4.19 (from medspacy_quickumls==3.2->medspacy)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: nltk>=3.3 in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (3.9.1)
Collecting pysimstring (from medspacy_quickumls==3.2->medspacy)
  Downloading pysimstring-1.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (931 bytes)
Collecting medspacy_unqlite>=0.8.1 (from medspacy_quickumls==3.2->medspacy)
  Downloading medspacy_unqlite-0.9.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: pytest>=6 in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (8.4.2)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from medspacy_quickumls==3.2->medspacy) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: Cython in /usr/local/lib/python3.12/dist-packages (from PyRuSH>=1.0.8->medspacy) (3.0.12)
Collecting PyFastNER>=1.0.8 (from PyRuSH>=1.0.8->medspacy)
  Downloading PyFastNER-1.0.10-py3-none-any.whl.metadata (15 kB)
Collecting quicksectx>=0.3.5 (from PyRuSH>=1.0.8->medspacy)
  Downloading quicksectx-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.7 kB)
Collecting loguru (from PyRuSH>=1.0.8->medspacy)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.3->scispacy) (3.6.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->medspacy) (0.30.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.3->medspacy_quickumls==3.2->medspacy) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.3->medspacy_quickumls==3.2->medspacy) (2025.11.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=6->medspacy_quickumls==3.2->medspacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading scispacy-0.6.2-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 4.6 MB/s eta 0:00:00
Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 65.1 MB/s eta 0:00:00
Downloading pysbd-0.3.4-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 5.3 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 50.7 MB/s eta 0:00:00
Downloading pyrush-1.0.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (547 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.9/547.9 kB 31.9 MB/s eta 0:00:00
Downloading conllu-6.0.0-py3-none-any.whl (16 kB)
Downloading medspacy_unqlite-0.9.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (408 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 408.5/408.5 kB 23.9 MB/s eta 0:00:00
Downloading pybind11-3.0.2-py3-none-any.whl (310 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.2/310.2 kB 20.9 MB/s eta 0:00:00
Downloading PyFastNER-1.0.10-py3-none-any.whl (22 kB)
Downloading quicksectx-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 41.1 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 19.4 MB/s eta 0:00:00
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 5.2 MB/s eta 0:00:00
Downloading pysimstring-1.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 51.5 MB/s eta 0:00:00
Building wheels for collected packages: medspacy, medspacy_quickumls, negspacy
  Building wheel for medspacy (pyproject.toml) ... done
  Created wheel for medspacy: filename=medspacy-1.3.1-py3-none-any.whl size=313705 sha256=08d8ddd766265b7e2c2052cc760045946a82e145252b14db7d38d3d5c8a70d88
  Stored in directory: /root/.cache/pip/wheels/54/ad/fd/49994aa138989a814164fed5afc6d8c7c3f1329d0aa0f327da
  Building wheel for medspacy_quickumls (setup.py) ... done
  Created wheel for medspacy_quickumls: filename=medspacy_quickumls-3.2-py3-none-any.whl size=98385 sha256=5b60e62262153ddc23358deb802a087f0bbc6cb218b07580d9c2615c5c45d8cb
  Stored in directory: /root/.cache/pip/wheels/5b/b8/96/ba72adae50099aa20ee8b11952fff415c8b82d86ca44528c92
  Building wheel for negspacy (pyproject.toml) ... done
  Created wheel for negspacy: filename=negspacy-1.0.4-py3-none-any.whl size=12630 sha256=0f262b2359396c532351ef68a9eadf3550ffd5599db1792bb3659040470521d4
  Stored in directory: /root/.cache/pip/wheels/ca/89/69/61a6a722e19bb58f0ccdb62d879ec1dc4513310059d1fc0d1a
Successfully built medspacy medspacy_quickumls negspacy
Installing collected packages: pysimstring, medspacy_unqlite, unidecode, quicksectx, pysbd, pybind11, numpy, loguru, conllu, PyFastNER, nmslib-metabrainz, scispacy, PyRuSH, negspacy, medspacy_quickumls, medspacy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed PyFastNER-1.0.10 PyRuSH-1.0.12 conllu-6.0.0 loguru-0.7.3 medspacy-1.3.1 medspacy_quickumls-3.2 medspacy_unqlite-0.9.8 negspacy-1.0.4 nmslib-metabrainz-2.1.3 numpy-1.26.4 pybind11-3.0.2 pysbd-0.3.4 pysimstring-1.3.0 quicksectx-0.4.1 scispacy-0.6.2 unidecode-1.4.0

In [ ]:
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz (119.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 MB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.8.0,>=3.7.4 (from en_core_sci_md==0.5.4)
  Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.12)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.4.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (26.0)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading langcodes-3.5.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2026.2.25)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4)
  Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.1.5)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.0.4)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_core_sci_md==0.5.4) (0.1.2)
Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 26.6 MB/s eta 0:00:00
Downloading langcodes-3.5.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 3.9 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (865 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.0/865.0 kB 13.4 MB/s eta 0:00:00
Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 20.5 MB/s eta 0:00:00
Building wheels for collected packages: en_core_sci_md
  Building wheel for en_core_sci_md (setup.py) ... done
  Created wheel for en_core_sci_md: filename=en_core_sci_md-0.5.4-py3-none-any.whl size=119157918 sha256=f4e73d6058021a366b065fd5a9e0178f1b8f0da53cf23558d04480deec6e3fa6
  Stored in directory: /root/.cache/pip/wheels/1a/02/d9/4d4bda80f6b73c02ed057d4b3b99abaff286924a80b53c9d68
Successfully built en_core_sci_md
Installing collected packages: langcodes, blis, thinc, spacy, en_core_sci_md
  Attempting uninstall: blis
    Found existing installation: blis 1.3.3
    Uninstalling blis-1.3.3:
      Successfully uninstalled blis-1.3.3
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.10
    Uninstalling thinc-8.3.10:
      Successfully uninstalled thinc-8.3.10
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.11
    Uninstalling spacy-3.8.11:
      Successfully uninstalled spacy-3.8.11
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyrush 1.0.12 requires spacy>=3.8; python_version >= "3.12", but you have spacy 3.7.5 which is incompatible.
medspacy 1.3.1 requires spacy<4.0,>=3.8; python_version >= "3.12", but you have spacy 3.7.5 which is incompatible.
Successfully installed blis-0.7.11 en_core_sci_md-0.5.4 langcodes-3.5.1 spacy-3.7.5 thinc-8.2.5

In [ ]:
import pandas as pd
import numpy as np
import re
import spacy
import scispacy
from negspacy.negation import Negex
from negspacy.termsets import termset

In [ ]:
CXR_DISEASE_VOCAB = {
    "pneumonia", "pneumothorax", "pleural_effusion", "atelectasis",
    "cardiomegaly", "edema", "emphysema", "fibrosis", "consolidation",
    "opacity", "nodule", "mass", "infiltrate", "effusion",
    "airspace_disease", "interstitial_disease", "injury"
}

In [ ]:
cxray_nlp = spacy.load("en_core_sci_md")
custom_termset = termset('en_clinical')
add_neg_patterns = custom_termset.get_patterns()
add_neg_patterns['following_negations'].extend( ["not seen", "not visualized", "not identified", "absent"])
add_neg_patterns['preceding_negations'].extend(["no evidence of", "without evidence of", "negative for", "free of"])
# add_neg_patterns["termination"].extend([";", "however", "but", "though"])

cxray_nlp.add_pipe(
    "negex",
    config={
        "ent_types": ["ENTITY"],
        'neg_termset':add_neg_patterns
    },
    last=True
)

/usr/local/lib/python3.12/dist-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [ ]:
custom_termset.get_patterns()

{'pseudo_negations': ['no further',
  'not able to be',
  'not certain if',
  'not certain whether',
  'not necessarily',
  'without any further',
  'without difficulty',
  'without further',
  'might not',
  'not only',
  'no increase',
  'no significant change',
  'no change',
  'no definite change',
  'not extend',
  'not cause',
  'gram negative',
  'not rule out',
  'not ruled out',
  'not been ruled out',
  'not drain',
  'no suspicious change',
  'no interval change',
  'no significant interval change'],
 'preceding_negations': ['absence of',
  'declined',
  'denied',
  'denies',
  'denying',
  'no sign of',
  'no signs of',
  'not',
  'not demonstrate',
  'symptoms atypical',
  'doubt',
  'negative for',
  'no',
  'versus',
  'without',
  "doesn't",
  'doesnt',
  "don't",
  'dont',
  "didn't",
  'didnt',
  "wasn't",
  'wasnt',
  "weren't",
  'werent',
  "isn't",
  'isnt',
  "aren't",
  'arent',
  'cannot',
  "can't",
  'cant',
  "couldn't",
  'couldnt',
  'never',
  'patient was not',
  'without indication of',
  'without sign of',
  'without signs of',
  'without any reactions or signs of',
  'no complaints of',
  'no evidence of',
  'no cause of',
  'evaluate for',
  'fails to reveal',
  'free of',
  'never developed',
  'never had',
  'did not exhibit',
  'rules out',
  'rule out',
  'rule him out',
  'rule her out',
  'rule patient out',
  'rule the patient out',
  'ruled out',
  'ruled him out',
  'ruled her out',
  'ruled patient out',
  'ruled the patient out',
  'r/o',
  'ro',
  'no evidence of',
  'without evidence of',
  'negative for',
  'free of',
  'no evidence of',
  'without evidence of',
  'negative for',
  'free of'],
 'following_negations': ['declined',
  'unlikely',
  'was not',
  'were not',
  "wasn't",
  'wasnt',
  "weren't",
  'werent',
  'was ruled out',
  'were ruled out',
  'free',
  'not seen',
  'not visualized',
  'not identified',
  'absent',
  'not seen',
  'not visualized',
  'not identified',
  'absent'],
 'termination': ['although',
  'apart from',
  'as there are',
  'aside from',
  'but',
  'except',
  'however',
  'involving',
  'nevertheless',
  'still',
  'though',
  'which',
  'yet',
  'cause for',
  'cause of',
  'causes for',
  'causes of',
  'etiology for',
  'etiology of',
  'origin for',
  'origin of',
  'origins for',
  'origins of',
  'other possibilities of',
  'reason for',
  'reason of',
  'reasons for',
  'reasons of',
  'secondary to',
  'source for',
  'source of',
  'sources for',
  'sources of',
  'trigger event for']}

In [ ]:
# minimal cleaning that is required for NER
def minimal_clean(text):

  text = re.sub(r"\s+", " ", text)  # remove multiple spaces
  text = re.sub(r"X{2,}", "", text) # remove PHI Masking
  text = text.lower()
  text = text.strip()

  return text

In [ ]:
def normalize_entity(text):
  ''' Need to normalize returned entity text to
  make it consistent for use as a label '''

  text = text.lower()
  text = text.strip()

  text = re.sub(r"[^a-z0-9\s\-]", "", text)  # keep only letters, digits, hyphen, space
  text = re.sub(r"\s+", "_", text)  # replace space with underscore

  return text

In [ ]:
def extract_labels(text, nlp):

  clean_text = minimal_clean(text)

  doc = nlp(clean_text) # extract affirmation/negation for suspected condition

  affirmed_conditions = set()
  negated_conditions = set()

  for entity in doc.ents:
    label = normalize_entity(entity.text)

    if label not in CXR_DISEASE_VOCAB:
      continue

    if len(label) < 4:
      continue

    if entity._.negex:
      negated_conditions.add(label)
    else:
      affirmed_conditions.add(label)

  return affirmed_conditions, negated_conditions

In [ ]:
#text = 'trachea is midline. the cardiomediastinal silhouette is normal. the lungs are clear without evidence of acute infiltrate or effusion. there is no pneumothorax. the visualized bony structures reveal no acute abnormality. no acute cardiopulmonary abnormality.'
texts =[
    'No pneumothorax is identified; however, there is a small pleural effusion.',
    'The lungs are clear without focal consolidation, but mild cardiomegaly is present.',
    'No pleural effusion, pneumothorax, or consolidation is seen.',
    'There is no evidence of edema or pneumonia; atelectasis is noted at the left base.',
    'Pleural effusion is not seen, and pneumothorax is not identified.',
    'Consolidation is absent, though patchy opacity is present.',
    'A small pneumothorax cannot be excluded.',
    'Findings are suspicious for pneumonia; however, pleural effusion is not definitively seen.',
    'No pleural effusion, pneumothorax, or consolidation is seen.',
    'No evidence of pneumonia, edema, or atelectasis.',
    'The study shows no infiltrate, mass, or nodule.',
    'No focal consolidation, pleural effusion, pneumothorax, or acute abnormality'
]
for text in texts:
  doc = cxray_nlp(text)
  for e in doc.ents:
    if normalize_entity(e.text) in CXR_DISEASE_VOCAB:
        print(e.text, e.label_, "negex=", e._.negex)
  print("==========")

pneumothorax ENTITY negex= True
pleural effusion ENTITY negex= False
==========
cardiomegaly ENTITY negex= False
==========
pleural effusion ENTITY negex= True
pneumothorax ENTITY negex= True
consolidation ENTITY negex= True
==========
edema ENTITY negex= True
pneumonia ENTITY negex= True
atelectasis ENTITY negex= True
==========
Pleural effusion ENTITY negex= True
pneumothorax ENTITY negex= True
==========
Consolidation ENTITY negex= True
==========
pneumothorax ENTITY negex= False
==========
pneumonia ENTITY negex= False
pleural effusion ENTITY negex= False
==========
pleural effusion ENTITY negex= True
pneumothorax ENTITY negex= True
consolidation ENTITY negex= True
==========
pneumonia ENTITY negex= True
edema ENTITY negex= True
atelectasis ENTITY negex= True
==========
infiltrate ENTITY negex= True
mass ENTITY negex= True
nodule ENTITY negex= True
==========
pleural effusion ENTITY negex= True
pneumothorax ENTITY negex= True
==========

In [ ]:
def get_entities(text):
  affirmed, negated = extract_labels(text, cxray_nlp)
  return affirmed, negated

In [ ]:
text = 'trachea is midline. the cardiomediastinal silhouette is normal. the lungs are clear without evidence of acute infiltrate or effusion. there is no pneumothorax. the visualized bony structures reveal no acute abnormality. no acute cardiopulmonary abnormality.'
a, n = get_entities(text)
print(f'Affirmed: {a}')
print(f'negated: {n}')

Affirmed: set()
negated: {'pneumothorax', 'effusion'}

### Evaluation Parameters

### 1. Coverage

In [ ]:
test_report = 'The cardiomediastinal silhouette and pulmonary vasculature are within normal limits. There is no pneumothorax or pleural effusion. There are no focal areas of consolidation. Small T-spine osteophytes.'

In [ ]:
evidence_set = [
  'case 1: trachea is midline. the cardiomediastinal silhouette is normal. the lungs are clear without evidence of acute infiltrate or effusion. there is no pneumothorax. the visualized bony structures reveal no acute abnormality. no acute cardiopulmonary abnormality.',
 'case 2: the heart size is upper limits of normal. the pulmonary and mediastinum are within normal limits. there is no pleural effusion or pneumothorax. there is mild streaky perihilar opacity without confluent airspace opacity to suggest a bacterial pneumonia. minimal perihilar opacity which could indicate an atypical pneumonia.',
 'case 3: heart size and mediastinal contours are within normal limits. there is no pneumothorax, pleural effusion, focal airspace consolidation. no acute cardiopulmonary findings.',
 'case 4: the cardiomediastinal silhouette and pulmonary vasculature are within normal limits in size. the lungs are clear of focal airspace disease, pneumothorax, or pleural effusion. there are no acute bony findings. no acute cardiopulmonary findings.',
 'case 5: the heart, pulmonary and mediastinum are within normal limits. there is no pleural effusion or pneumothorax. there is no focal air space opacity to suggest a pneumonia. there are mild degenerative changes of the spine. no acute cardiopulmonary disease.'
 ]

In [ ]:
aff_test, neg_test = extract_labels(test_report, cxray_nlp)
print(f'Affirmed: {aff_test}')
print(f'negated: {neg_test}')

Affirmed: set()
negated: {'pneumothorax', 'consolidation', 'pleural_effusion'}

In [ ]:
aff_ent_evd = set()
neg_ent_evd = set()

for text in evidence_set:
  aff_evd, neg_evd = extract_labels(text, cxray_nlp)
  aff_ent_evd.update(aff_test)
  neg_ent_evd.update(neg_evd)

print(f'Affirmed Entities: {aff_ent_evd}')
print(f'Negated Entities: {neg_ent_evd}')

Affirmed Entities: set()
Negated Entities: {'opacity', 'pneumonia', 'pneumothorax', 'effusion', 'pleural_effusion'}

In [ ]:
#generated report
gen_report = '''No acute cardiopulmonary abnormality. Lungs are clear without evidence of infiltrate, effusion, pneumothorax, or focal airspace disease. Heart size and mediastinum are within normal limits. Mild degenerative changes of the spine noted.
Based on evidence from multiple cases stating 'no acute cardiopulmonary abnormality,' 'lungs are clear without evidence of acute infiltrate or effusion,' 'no pneumothorax,' 'heart and mediastinum are within normal limits,' and 'mild degenerative changes of the spine' as in case 5.
'''
aff_gen_report, neg_gen_report = extract_labels(gen_report, cxray_nlp)
print(f'Affirmed: {aff_gen_report}')
print(f'negated: {neg_gen_report}')

Affirmed: set()
negated: {'pneumothorax', 'infiltrate', 'effusion'}

### Test Cases

In [ ]:
import pickle
import json
import re

In [ ]:
def extract_impression(llm_output):
    match = re.search(r"\{.*\}", llm_output, re.DOTALL)
    parsed = json.loads(match.group())
    return parsed["impression"]

In [ ]:
with open('/content/drive/MyDrive/comp-final-project/test_results_v3.pkl','rb') as f:
  test_results = pickle.load(f)

In [ ]:
test_results[1001]['diagnosis']

'the lungs are clear. there is no pleural effusion. the heart is normal. there are atherosclerotic changes of the aorta. senescent changes of the spine are seen. no acute pulmonary disease.'

In [ ]:
test_results[1]

{'case_id': 1,
 'diagnosis': 'the cardiac silhouette and mediastinum size are within normal limits. there is no pulmonary edema. there is no focal consolidation. there are no of a pleural effusion. there is no evidence of pneumothorax. normal chest x .',
 'evidence_set': ['case 1: heart size and mediastinal contour are normal. pulmonary vascularity is normal. lungs are hyperexpanded but clear. no pleural effusions or pneumothoraces. degenerative changes in the thoracic spine. findings suggestive of emphysema. no acute cardiopulmonary process.',
  'case 2: there are scattered calcified granulomas. no focal infiltrate. no pleural effusion or pneumothorax. heart size and mediastinal contour are within normal limits. there are degenerative changes of the spine. no evidence of active disease.',
  'case 3: mild hyperexpansion of the lungs. numerous bilateral rib deformities. no focal airspace disease. heart size is normal. no pneumothorax or effusion. large, flowing anterior endplate osteophytes of the thoracic spine. emphysema with no acute cardiopulmonary findings.',
  'case 4: the examination consists of frontal and lateral radiographs of the chest. the cardiomediastinal contours are within normal limits. pulmonary vascularity is within normal limits. no focal consolidation, pleural effusion, or pneumothorax identified. deformity of the right clavicle related to remote is again seen. visualized upper abdomen grossly unremarkable. no evidence of acute cardiopulmonary process.',
  'case 5: the examination consists of frontal and lateral radiographs of the chest. the cardiomediastinal contours are within normal limits. pulmonary vascularity is within normal limits. no focal consolidation, pleural effusion, or pneumothorax identified. multilevel degenerative changes are seen throughout the thoracic spine.  anchors over the left humeral head. there is mild bilateral acromioclavicular joint osteoarthritis. visualized upper abdomen is grossly unremarkable in appearance. no evidence of acute cardiopulmonary process.'],
 'gen_report': '{\n  "impression": "Normal cardiomediastinal contours and pulmonary vascularity with no evidence of acute cardiopulmonary process. Deformity of the right clavicle related to remote trauma again seen.",\n  "confidence": "High",\n  "outlier_note": ""\n}'}

In [ ]:
test_results[1001]['gen_report']

'```json\n{\n  "impression": "No acute cardiopulmonary abnormality detected. Lungs are clear without evidence of infiltrate, effusion, or pneumothorax. Heart size and mediastinal contours are within normal limits. Mild degenerative changes of the spine noted.",\n  "reasoning": "Evidence shows multiple cases describing no acute cardiopulmonary abnormalities (e.g., \'no acute cardiopulmonary abnormality,\' \'no focal airspace consolidation,\' \'no pleural effusion or pneumothorax\'). Heart size is normal or at upper limits but without acute pathology (\'heart size and mediastinal contours are within normal limits,\' \'heart size is upper limits of normal\'). Mild spine degenerative changes are noted in case 5 (\'mild degenerative changes of the spine\').",\n  "confidence": "High",\n  "outlier_note": ""\n}\n```'

In [ ]:
result = test_results[0]

In [ ]:
# Affirmed Recall (Coverage): Did model cover true finding
def affirmed_recall(PS_aff, GT_aff):
  if len(GT_aff) == 0:
    return 1.0
  return len(PS_aff & GT_aff)/len(GT_aff)

# Affirmed Precision (Correctness):
def affirmed_precision(PS_aff, GT_aff):
  if len(PS_aff) == 0:
    return 1.0
  return len(PS_aff & GT_aff) / len(PS_aff)

# Polarity Flip Rate: Did we contrdict GT
def polarity_flip_count(PS_aff, GT_ng):
  return len(PS_aff & GT_ng)

# Evidence Support Rate: Was the output grounded
def evidence_support(PS_aff, ES_aff, ES_ng):
  if len(PS_aff) == 0:
    return 1.0
  supported = ES_aff | ES_ng
  return len(PS_aff & supported) / len(PS_aff)

# Hallucination wrt Ground Truth
def hallucination_wrt_gt(PS_aff, GT_aff):
  if len(PS_aff) == 0:
    return 0.0
  return len(PS_aff - GT_aff) / len(PS_aff)

#Hallucination wrt Evidence Set
def hallucination_ert_evd(PS_aff, ES_aff, ES_ng):
  if len(PS_aff) == 0:
    return 0.0
  supported = ES_aff | ES_ng
  return len(PS_aff - supported) / len(PS_aff)

# Negated Recall: Did model find normal findings
def negated_recall(PS_ng, GT_ng):
    if len(GT_ng) == 0:
        return 1.0
    return len(PS_ng & GT_ng) / len(GT_ng)

# Negated Precision
def negated_precision(PS_ng, GT_ng):
    if len(PS_ng) == 0:
        return 1.0
    return len(PS_ng & GT_ng) / len(PS_ng)

In [ ]:
len(test_results)

1288

In [ ]:
!pip install rouge_score

Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.26.4)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=b11f4cb784f7b0564aaa481437888c34c9976b9681bbbc0b81e49c4fd450d595
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2

In [ ]:

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

eval_metrics = {
    'coverage': 0.0,
    'precision':0.0,
    'pfc':0.0,
    'support':0.0,
    'hall_gt':0.0,
    'hall_evd':0.0,
    'ng_cvg':0.0,
    'ng_prc':0.0,
    'bleu':0.0,
    'rouge_1':0.0,
    'rouge_L':0.0,

  }
count = 0
for record in test_results:
  GT_aff, GT_ng = extract_labels(record['diagnosis'],cxray_nlp)
  ES_aff, ES_ng = extract_labels(" ".join(record['evidence_set']),cxray_nlp)

  gen_impression = extract_impression(record['gen_report'])
  PS_aff, PS_ng = extract_labels(gen_impression,cxray_nlp)

  cvg = affirmed_recall(PS_aff, GT_aff)
  prc = affirmed_precision(PS_aff, GT_aff)
  pfc = polarity_flip_count(PS_aff, GT_ng)
  supp = evidence_support(PS_aff, ES_aff, ES_ng)
  hall_gt = hallucination_wrt_gt(PS_aff, GT_aff)
  hall_evd = hallucination_ert_evd(PS_aff, ES_aff, ES_ng)
  neg_cvg = negated_recall(PS_ng, GT_ng)
  neg_prc = negated_precision(PS_ng, GT_ng)

  #BLEU
  reference = [record['diagnosis'].split()]
  candidate = (gen_impression.split())
  smoothie = SmoothingFunction().method4
  bleu = sentence_bleu(reference, candidate,
                        smoothing_function=smoothie)
  eval_metrics['bleu'] += bleu


  #Rouge
  reference = record['diagnosis']
  candidate = gen_impression

  scorer = rouge_scorer.RougeScorer(
      ['rouge1', 'rouge2', 'rougeL'],
      use_stemmer=True
  )

  scores = scorer.score(reference, candidate)
  eval_metrics['rouge_1'] += scores['rouge1'].fmeasure
  eval_metrics['rouge_L'] += scores['rougeL'].fmeasure

  eval_metrics['coverage'] += cvg
  eval_metrics['precision'] += prc
  eval_metrics['pfc'] += pfc
  eval_metrics['support'] += supp
  eval_metrics['hall_gt'] += hall_gt
  eval_metrics['hall_evd'] += hall_evd
  eval_metrics['ng_cvg'] += neg_cvg
  eval_metrics['ng_prc'] += neg_prc

  count += 1

  print(f'{count}: records processed')

eval_metrics

1: records processed
2: records processed
3: records processed
4: records processed
5: records processed
6: records processed
7: records processed
8: records processed
9: records processed
10: records processed
11: records processed
12: records processed
13: records processed
14: records processed
15: records processed
16: records processed
17: records processed
18: records processed
19: records processed
20: records processed
21: records processed
22: records processed
23: records processed
24: records processed
25: records processed
26: records processed
27: records processed
28: records processed
29: records processed
30: records processed
31: records processed
32: records processed
33: records processed
34: records processed
35: records processed
36: records processed
37: records processed
38: records processed
39: records processed
40: records processed
41: records processed
42: records processed

KeyboardInterrupt:

### Performance Evaluation on Test Cases

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [ ]:
import pandas as pd
import numpy as np
import random
import glob
import os
from google.colab import userdata
import os
from openai import OpenAI

In [ ]:
client = OpenAI(api_key = userdata.get('OPENAI_API_KEY'))

resp = client.responses.create(
    model = 'gpt-5.1',
    input = 'Hi, tell me a popular proverb'
)

In [ ]:
def get_percentage(eval_metrics, n):
  for k, v in eval_metrics.items():
    eval_metrics[k] = eval_metrics[k]/n *100

  return eval_metrics

In [ ]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer
def eval_performance(test_results):
  eval_metrics = {
    'coverage': 0.0,
    'precision':0.0,
    'pfc':0.0,
    'support':0.0,
    'hall_gt':0.0,
    'hall_evd':0.0,
    'ng_cvg':0.0,
    'ng_prc':0.0,
    'bleu':0.0,
    'rouge_1':0.0,
    'rouge_L':0.0
  }
  count = 0
  for record in test_results:
    GT_aff, GT_ng = extract_labels(record['diagnosis'],cxray_nlp)
    ES_aff, ES_ng = extract_labels(" ".join(record['evidence_set']),cxray_nlp)

    gen_impression = extract_impression(record['gen_report'])
    PS_aff, PS_ng = extract_labels(gen_impression,cxray_nlp)

    cvg = affirmed_recall(PS_aff, GT_aff)
    prc = affirmed_precision(PS_aff, GT_aff)
    pfc = polarity_flip_count(PS_aff, GT_ng)
    supp = evidence_support(PS_aff, ES_aff, ES_ng)
    hall_gt = hallucination_wrt_gt(PS_aff, GT_aff)
    hall_evd = hallucination_ert_evd(PS_aff, ES_aff, ES_ng)
    neg_cvg = negated_recall(PS_ng, GT_ng)
    neg_prc = negated_precision(PS_ng, GT_ng)

    #BLEU
    reference = [record['diagnosis'].split()]
    candidate = (gen_impression.split())
    smoothie = SmoothingFunction().method4
    bleu = sentence_bleu(reference, candidate,
                         smoothing_function=smoothie)
    eval_metrics['bleu'] += bleu


    #Rouge
    reference = record['diagnosis']
    candidate = gen_impression

    scorer = rouge_scorer.RougeScorer(
        ['rouge1', 'rouge2', 'rougeL'],
        use_stemmer=True
    )

    scores = scorer.score(reference, candidate)
    eval_metrics['rouge_1'] += scores['rouge1'].fmeasure
    eval_metrics['rouge_L'] += scores['rougeL'].fmeasure



    eval_metrics['coverage'] += cvg
    eval_metrics['precision'] += prc
    eval_metrics['pfc'] += pfc
    eval_metrics['support'] += supp
    eval_metrics['hall_gt'] += hall_gt
    eval_metrics['hall_evd'] += hall_evd
    eval_metrics['ng_cvg'] += neg_cvg
    eval_metrics['ng_prc'] += neg_prc

    count += 1

    print(f'{count}: records processed')

  return eval_metrics

In [ ]:
test_cases = random.choices(test_results, k=10)

In [ ]:
vis_rag_perf = eval_performance(test_cases)

1: records processed
2: records processed
3: records processed
4: records processed
5: records processed
6: records processed
7: records processed
8: records processed
9: records processed
10: records processed

In [ ]:
vis_rag_perf

{'coverage': 10.0,
 'precision': 10.0,
 'pfc': 0.0,
 'support': 10.0,
 'hall_gt': 0.0,
 'hall_evd': 0.0,
 'ng_cvg': 7.0,
 'ng_prc': 7.0,
 'bleu': 0.21750342710609932,
 'rouge_1': 3.4276775338240397,
 'rouge_L': 2.1034468467012637}

In [ ]:
vis_rag_metrics = get_percentage(vis_rag_perf,5)
vis_rag_metrics

{'coverage': 200.0,
 'precision': 200.0,
 'pfc': 0.0,
 'support': 200.0,
 'hall_gt': 0.0,
 'hall_evd': 0.0,
 'ng_cvg': 140.0,
 'ng_prc': 140.0,
 'bleu': 4.350068542121986,
 'rouge_1': 68.5535506764808,
 'rouge_L': 42.068936934025274}

In [ ]:
images_dir = '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/'

In [ ]:
case_ids =[]
for record in test_cases:
  case_ids.append(record['case_id'])

case_ids

[489, 55, 1636, 3946, 3094, 1630, 2717, 1220, 2343, 1966]

In [ ]:
matched_files = []

for cid in case_ids:
    pattern = os.path.join(images_dir, f"{cid}[_]*")
    matched_files.extend(glob.glob(pattern))
matched_files

['/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/253_IM-1045-1001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/253_IM-1045-2001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/1202_IM-0136-1001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/1202_IM-0136-2001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/3872_IM-1964-2001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/3872_IM-1964-1001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2457_IM-0989-2001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2457_IM-0989-1001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/884_IM-2398-1001.dcm.png',
 '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/884_IM-2398-1002.dcm.png']

In [ ]:
image_paths = ['/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/253_IM-1045-1001.dcm.png',
               '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/1202_IM-0136-1001.dcm.png',
               '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/3872_IM-1964-2001.dcm.png',
               '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/2457_IM-0989-2001.dcm.png',
               '/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/884_IM-2398-1001.dcm.png'
               ]

In [ ]:
for c in test_cases:
  print(f'Case: ')
  print(f'Diagnosis: {c['diagnosis']}')
  print(f'Report: {c['gen_report']}')
  print("\n")
  print("\n")

Case:
Diagnosis: cardiomediastinal silhouette is a within normal limits. no focal consolidation, pneumothorax, or pleural effusion. multiple granulomas. no acute bony abnormalities. no acute cardiopulmonary abnormalities. no acute bony abnormalities. if there is continued concern for occult fracture, consider dedicated rib series.
Report: {
  "impression": "No acute cardiopulmonary abnormality identified. Findings are compatible with prior granulomatous disease. \"no focal consolidation, large pleural effusion, or pneumothorax is identified\"; \"evidence of prior granulomatous disease\"; \"no acute cardiopulmonary abnormality.\"",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: lung lines remain low. however, no focal infiltrates are identified. heart and pulmonary are normal. change. hypoinflation with no visible active cardiopulmonary disease.
Report: {
  "impression": "No acute cardiopulmonary disease. Normal cardiomediastinal silhouette and clear lungs without pneumothorax, pleural effusion, or focal airspace consolidation. Degenerative spine changes.",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: lungs are clear. no pleural effusions or pneumothoraces. heart and mediastinum of normal size and contour. clear lungs.
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette is normal. Lungs are clear without focal consolidation, effusion, or pneumothorax.",
  "confidence": "High",
  "outlier_note": "",
  "evidence_quotes": [
    "no acute cardiopulmonary abnormality..",
    "the cardiomediastinal silhouette is normal.",
    "the lungs are clear, without evidence of focal infiltrate or effusion. there is no pneumothorax."
  ]
}




Case:
Diagnosis: there are no focal areas of consolidation. no suspicious pulmonary opacities. heart size within normal limits. no pleural effusions. there is no evidence of pneumothorax. osseous structures are intact. no acute cardiopulmonary abnormality.
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette and pulmonary vascularity are within normal limits. Osseous structures are grossly intact.",
  "confidence": "High",
  "outlier_note": "",
  "evidence_quotes": [
    "no acute cardiopulmonary process.",
    "heart size and pulmonary vascularity are within normal limits.",
    "osseous structures are grossly intact."
  ]
}




Case:
Diagnosis: heart size is normal. lungs are clear. low lung volumes. there is no pneumothorax or large pleural effusion. no acute cardiopulmonary findings.
Report: {
  "impression": "Minimal patchy left basilar atelectasis or early infiltrate. Heart size and mediastinal contours within normal limits. No visible pleural effusion or pneumothorax. Justified by: \"heart size and mediastinal contours are within normal limits given ap projection\", \"there is minimal patchy atelectasis or early infiltrate in left lung base\", \"no visible pleural effusion or pneumothorax\"",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: 2 images. there is a poorly defined lung nodule in the right upper lobe measuring approximately 7 mm and partially superimposed upon anterior right second rib. otherwise, the lungs are clear. no pleural effusion or pneumothorax. heart size is normal. critical result notification documented through primordial. 7 mm right upper lobe lung nodule. recommend followup characterization with .
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette is unremarkable. Visualized osseous structures of the thorax are without acute abnormality.",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: the cardiac contours are normal. the lungs are clear. thoracic spondylosis. no acute process.
Report: {
  "impression": "No acute cardiopulmonary process. Normal heart size and clear lungs without focal airspace disease, pleural effusion, or pneumothorax.",
  "confidence": "High",
  "outlier_note": "",
  "evidence_quotes": [
    "no acute radiographic cardiopulmonary process.",
    "normal heart size and hilar vascular markings.",
    "the lungs are clear without focal area of consolidation, pleural effusion, pneumothorax."
  ]
}




Case:
Diagnosis: there is hyperexpansion, hyperlucency of both lungs, as well as flattening of the diaphragm consistent with chronic emphysematous lung disease. no focal consolidation, pneumothorax, or large pleural effusion identified blunting of costophrenic recesses bilaterally may represent small effusions or pleural thickening scar. stable calcified mediastinal and hilar lymph and a left basilar calcified granuloma. acute osseous abnormality. the mediastinal silhouette stable. changes of chronic emphysematous lung disease without acute cardiopulmonary abnormality identified.
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette is unremarkable and the lungs are clear bilaterally. Visualized osseous structures of the thorax are without acute abnormality.",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: the lungs are clear. there is no pleural effusion or pneumothorax. the heart is not significantly enlarged. there are atherosclerotic changes of the aorta. arthritic changes of the skeletal structures are noted. no acute pulmonary disease.
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette is unremarkable and lungs are clear without focal consolidation, pneumothorax, or pleural effusion. Visualized osseous structures are without acute abnormality.",
  "confidence": "High",
  "outlier_note": ""
}




Case:
Diagnosis: the heart is normal in size. the mediastinum is unremarkable. the lungs are clear. no acute disease.
Report: {
  "impression": "No acute cardiopulmonary abnormality. Cardiomediastinal silhouette within normal limits. Stable appearing bilateral calcified lymph nodes.",
  "confidence": "High",
  "outlier_note": ""
}

### Report Generation Using Templates

In [ ]:
!pip -q install jinja2 reportlab

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 21.8 MB/s eta 0:00:00

In [ ]:
from jinja2 import Template
XRAY_REPORT_TEMPLATE = Template (
"""
AI-Assisted Clinical Decision Support System
CHEST X-RAY SUGGESTIVE DIAGNOSIS REPORT


Patient Name: {{ patient_name }}
Age: {{ age }}


IMPRESSION:
{{ impression }}


Generated by: {{ generator_name }}


This report is AI-assisted and intended for research purposes only.
""".strip()
)

In [ ]:
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import Image, Spacer, Paragraph
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate
from PIL import Image as PILImage
from reportlab.platypus import HRFlowable
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER

def render_report(data):
  return XRAY_REPORT_TEMPLATE.render(
      patient_name = data['patient_name'],
      age = data['age'],
      impression = data['impression'],
      generator_name = 'Visaul RAG System'
 )


def save_report_pdf_v2(report_text: str, cxr_image_path, out_path: str):

    styles = getSampleStyleSheet()

    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Normal'],
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        spaceAfter=12,
    )

    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=12,
        leading=16,
    )

    doc = SimpleDocTemplate(
        out_path,
        pagesize=LETTER,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    story = []

    blocks = report_text.split("\n\n")

    for i, block in enumerate(blocks):
        block = block.strip().replace("\n", "<br/>")

        if block:
            if i == 0:
                story.append(Paragraph(f"<b>{block}</b>", header_style))
                story.append(HRFlowable(
                          width="100%",
                          thickness=1,
                          lineCap='round',
                          color=colors.black,
                          spaceBefore=6,
                          spaceAfter=6
                      ))
            elif i == len(blocks) - 1:
              story.append(HRFlowable(
                                    width="100%",
                                    thickness=1,
                                    lineCap='round',
                                    color=colors.black,
                                    spaceBefore=6,
                                    spaceAfter=6
                                ))
              story.append(Paragraph(block, body_style))
            else:
                story.append(Paragraph(block, body_style))

            story.append(Spacer(1, 20))


        if i == 0 and cxr_image_path:
            pil_img = PILImage.open(cxr_image_path)
            w, h = pil_img.size
            aspect = h / w

            max_w = 6.0 * inch
            img = Image(cxr_image_path, width=max_w, height=max_w * aspect)

            story.append(Spacer(1, 8))
            story.append(img)
            story.append(Spacer(1, 14))



    doc.build(story)

In [ ]:
report_data = {
    "patient_name": "Mary Jane",
    "age": 68,
    "impression": "No acute cardiopulmonary abnormality identified. Findings are compatible with prior granulomatous disease. No focal consolidation, large pleural effusion, or pneumothorax is identified. Evidence of prior granulomatous disease. No acute cardiopulmonary abnormality.",
    "generator_name": "AI-Assisted Clinical Decision Support System",
}

report_name = 'VRAG_XRAY_DIAG'
img_id = "489_IM-2110-1001.dcm.png"
cxr_img_path = f'/content/drive/MyDrive/comp-final-project/chest-xrays/images/images_normalized/{img_id}'
text = render_report(report_data)
filename = f'{report_name}_CXR_Report.pdf'
save_report_pdf_v2(text, cxr_img_path ,filename)

filename

'VRAG_XRAY_DIAG_CXR_Report.pdf'

In [1]:
!pip freeze > requirements.txt